// Known failures for the full-corpus suite (#108 Phase 4), keyed by
// `<testSet-relative-path>/<testGroup>/<instanceTest>`. Entries run as
// `it.fails` — a fix that makes a case pass turns the suite red; remove the
// entry in the same PR. Generated from full corpus runs, then hand-maintained.
export const W3C_CORPUS_REASONS = {
  choiceValidation:
    "nested choice groups: inner choice is enforced even when its outer branch is not selected (needs occurrence-aware validation)",
  libxmlRejectsSerialized: "libxml2 rejects serialized XML (needs triage)",
  patternTranslation: "codegen: XSD pattern facet regex translation too strict (needs triage)",
  wildcard: "unsupported: xs:any wildcard content",
  strictWildcardHarness:
    "strict wildcard: extras re-serialized faithfully, but single-schema libxml2 validation cannot see cross-file declarations (harness limitation)",
  needsTriage: "needs triage",
  undefinedValue: "parse: element value arrives as undefined (needs triage)",
  requiredArrayEmpty: "cardinality: required element array parsed empty (needs triage)",
  patternOnNonString:
    "runtime: pattern checked against coerced value, not the original lexical (lexical preservation needed)",
  substitutionGroups: "unsupported: substitution groups",
  anyTypeContent: "unsupported: xs:anyType content (element without a type maps to xs:string)",
  regexTranslation:
    "codegen: XSD regex syntax not translatable to JS RegExp (char class subtraction etc.)",
  simpleContentShape: "parse: simpleContent _text shape mismatch (needs triage)",
} as const;

export const W3C_CORPUS_KNOWN_FAILURES = new Map<string, string>([
  ["boeingMeta/BoeingXSDTestSet.testSet/ipo6/ipo_2", W3C_CORPUS_REASONS.substitutionGroups],
  ["msMeta/Additional_w3c.xml/addA005/addA005.v", W3C_CORPUS_REASONS.choiceValidation],
  ["msMeta/Additional_w3c.xml/addB012/addB012.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Additional_w3c.xml/addB058/addB058.v", W3C_CORPUS_REASONS.patternTranslation],
  ["msMeta/Additional_w3c.xml/addB067/addB067.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Additional_w3c.xml/addB068/addB068.i", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Additional_w3c.xml/addB090/addB090.v", W3C_CORPUS_REASONS.wildcard],
  ["msMeta/Additional_w3c.xml/addB116/addB116.v", W3C_CORPUS_REASONS.strictWildcardHarness],
  ["msMeta/Additional_w3c.xml/addB135/addB135.v", W3C_CORPUS_REASONS.wildcard],
  ["msMeta/Additional_w3c.xml/addB187/addB187.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/Additional_w3c.xml/addC001/addC001.v", W3C_CORPUS_REASONS.undefinedValue],
  ["msMeta/Additional_w3c.xml/isDefault072/isDefault072.v", W3C_CORPUS_REASONS.undefinedValue],
  [
    "msMeta/Additional_w3c.xml/isDefault078/isDefault078.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  ["msMeta/Additional_w3c.xml/isDefault079/isDefault079.v", W3C_CORPUS_REASONS.needsTriage],
  [
    "msMeta/Additional_w3c.xml/memberType004/memberType004.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/Additional_w3c.xml/memberType008/memberType008.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  ["msMeta/AttributeGroup_w3c.xml/attgD019/attgD019.v", W3C_CORPUS_REASONS.strictWildcardHarness],
  ["msMeta/AttributeGroup_w3c.xml/attgD020/attgD020.v", W3C_CORPUS_REASONS.strictWildcardHarness],
  ["msMeta/AttributeGroup_w3c.xml/attgD021/attgD021.v", W3C_CORPUS_REASONS.strictWildcardHarness],
  ["msMeta/AttributeGroup_w3c.xml/attgD022/attgD022.v", W3C_CORPUS_REASONS.strictWildcardHarness],
  ["msMeta/AttributeGroup_w3c.xml/attgD025/attgD025.v", W3C_CORPUS_REASONS.strictWildcardHarness],
  ["msMeta/AttributeGroup_w3c.xml/attgD034/attgD034.v", W3C_CORPUS_REASONS.strictWildcardHarness],
  ["msMeta/Attribute_w3c.xml/attO009/attO009.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/Attribute_w3c.xml/attO010/attO010.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/Attribute_w3c.xml/attO011/attO011.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/ComplexType_w3c.xml/ctA002/ctA002.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/ComplexType_w3c.xml/ctA003/ctA003.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/ComplexType_w3c.xml/ctL021/ctL021.v", W3C_CORPUS_REASONS.strictWildcardHarness],
  ["msMeta/ComplexType_w3c.xml/ctL022/ctL022.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/ComplexType_w3c.xml/ctZ007/ctZ007.v", W3C_CORPUS_REASONS.requiredArrayEmpty],
  [
    "msMeta/DataTypes_w3c.xml/QName006_2089/QName006_2089.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/DataTypes_w3c.xml/QName_enumeration002_1369/QName_enumeration002_1369.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/DataTypes_w3c.xml/QName_enumeration004_1371/QName_enumeration004_1371.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/DataTypes_w3c.xml/gMonth002_2061/gMonth002_2061.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/DataTypes_w3c.xml/gMonth004_2063/gMonth004_2063.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  ["msMeta/Element_w3c.xml/QFE1700c2/QFE1700c2.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/Element_w3c.xml/elemS002/elemS002.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/Element_w3c.xml/elemS003/elemS003.v", W3C_CORPUS_REASONS.substitutionGroups],
  ["msMeta/Element_w3c.xml/elemS007/elemS007.v", W3C_CORPUS_REASONS.substitutionGroups],
  ["msMeta/Element_w3c.xml/elemS008/elemS008.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/Element_w3c.xml/elemU006/elemU006.v", W3C_CORPUS_REASONS.patternTranslation],
  ["msMeta/Element_w3c.xml/elemU007/elemU007.v", W3C_CORPUS_REASONS.patternTranslation],
  ["msMeta/Element_w3c.xml/elemZ021d/elemZ021d.v", W3C_CORPUS_REASONS.anyTypeContent],
  ["msMeta/Errata10_w3c.xml/errC001/errC001.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/Group_w3c.xml/groupF009v/groupF009v.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Group_w3c.xml/groupG004v/groupG004v.v", W3C_CORPUS_REASONS.requiredArrayEmpty],
  ["msMeta/Group_w3c.xml/groupH009v/groupH009v.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Group_w3c.xml/groupH011v/groupH011v.v", W3C_CORPUS_REASONS.choiceValidation],
  ["msMeta/Group_w3c.xml/groupH014v/groupH014v.v", W3C_CORPUS_REASONS.choiceValidation],
  ["msMeta/Group_w3c.xml/groupH017v/groupH017v.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/Group_w3c.xml/groupH018v/groupH018v.v", W3C_CORPUS_REASONS.choiceValidation],
  ["msMeta/Group_w3c.xml/groupJ009v/groupJ009v.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Group_w3c.xml/groupL009v/groupL009v.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Group_w3c.xml/groupN009v/groupN009v.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/IdentityConstraint_w3c.xml/idF012/idF012.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/IdentityConstraint_w3c.xml/idF013/idF013.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/IdentityConstraint_w3c.xml/idF014/idF014.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/IdentityConstraint_w3c.xml/idF026/idF026.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/IdentityConstraint_w3c.xml/idF031/idF031.v", W3C_CORPUS_REASONS.undefinedValue],
  ["msMeta/IdentityConstraint_w3c.xml/idG030/idG030.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/ModelGroups_w3c.xml/mgA015/mgA015.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/ModelGroups_w3c.xml/mgF010/mgF010.v", W3C_CORPUS_REASONS.wildcard],
  ["msMeta/ModelGroups_w3c.xml/mgF011/mgF011.v", W3C_CORPUS_REASONS.wildcard],
  ["msMeta/ModelGroups_w3c.xml/mgF012/mgF012.v", W3C_CORPUS_REASONS.wildcard],
  ["msMeta/ModelGroups_w3c.xml/mgF014/mgF014.v", W3C_CORPUS_REASONS.wildcard],
  ["msMeta/ModelGroups_w3c.xml/mgF019/mgF019.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/ModelGroups_w3c.xml/mgI009/mgI009.v", W3C_CORPUS_REASONS.choiceValidation],
  ["msMeta/ModelGroups_w3c.xml/mgI010/mgI010.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/ModelGroups_w3c.xml/mgI011/mgI011.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/ModelGroups_w3c.xml/mgI012/mgI012.v", W3C_CORPUS_REASONS.choiceValidation],
  ["msMeta/ModelGroups_w3c.xml/mgI013/mgI013.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/ModelGroups_w3c.xml/mgI014/mgI014.v", W3C_CORPUS_REASONS.choiceValidation],
  ["msMeta/ModelGroups_w3c.xml/mgI015/mgI015.v", W3C_CORPUS_REASONS.choiceValidation],
  ["msMeta/ModelGroups_w3c.xml/mgI016/mgI016.v", W3C_CORPUS_REASONS.anyTypeContent],
  ["msMeta/ModelGroups_w3c.xml/mgI017/mgI017.v", W3C_CORPUS_REASONS.anyTypeContent],
  ["msMeta/ModelGroups_w3c.xml/mgI018/mgI018.v", W3C_CORPUS_REASONS.choiceValidation],
  ["msMeta/ModelGroups_w3c.xml/mgO006/mgO006.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/ModelGroups_w3c.xml/mgQ002/mgQ002.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/ModelGroups_w3c.xml/mgQ003/mgQ003.v", W3C_CORPUS_REASONS.choiceValidation],
  ["msMeta/Notations_w3c.xml/notatH001v/notatH001v.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  [
    "msMeta/Particles_w3c.xml/particlesA006/particlesA006.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/Particles_w3c.xml/particlesA007/particlesA007.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  ["msMeta/Particles_w3c.xml/particlesB013/particlesB013.v", W3C_CORPUS_REASONS.wildcard],
  ["msMeta/Particles_w3c.xml/particlesDc001/particlesDc001.v", W3C_CORPUS_REASONS.anyTypeContent],
  ["msMeta/Particles_w3c.xml/particlesDc002/particlesDc002.v", W3C_CORPUS_REASONS.anyTypeContent],
  ["msMeta/Particles_w3c.xml/particlesDc003/particlesDc003.v", W3C_CORPUS_REASONS.anyTypeContent],
  ["msMeta/Particles_w3c.xml/particlesDc007/particlesDc007.v", W3C_CORPUS_REASONS.anyTypeContent],
  [
    "msMeta/Particles_w3c.xml/particlesEb027/particlesEb027.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/Particles_w3c.xml/particlesEb036/particlesEb036.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/Particles_w3c.xml/particlesEb038/particlesEb038.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  ["msMeta/Particles_w3c.xml/particlesHa015/particlesHa015.v", W3C_CORPUS_REASONS.anyTypeContent],
  ["msMeta/Particles_w3c.xml/particlesIb005/particlesIb005.v", W3C_CORPUS_REASONS.anyTypeContent],
  [
    "msMeta/Particles_w3c.xml/particlesJs001/particlesJs001.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  ["msMeta/Particles_w3c.xml/particlesOb003/particlesOb003.v", W3C_CORPUS_REASONS.wildcard],
  ["msMeta/Particles_w3c.xml/particlesOb006/particlesOb006.v", W3C_CORPUS_REASONS.wildcard],
  ["msMeta/Particles_w3c.xml/particlesOb007/particlesOb007.v", W3C_CORPUS_REASONS.wildcard],
  ["msMeta/Particles_w3c.xml/particlesOb012/particlesOb012.v", W3C_CORPUS_REASONS.wildcard],
  ["msMeta/Particles_w3c.xml/particlesOb015/particlesOb015.v", W3C_CORPUS_REASONS.wildcard],
  [
    "msMeta/Particles_w3c.xml/particlesOb022/particlesOb022.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/Particles_w3c.xml/particlesOb042/particlesOb042.v",
    W3C_CORPUS_REASONS.strictWildcardHarness,
  ],
  ["msMeta/Particles_w3c.xml/particlesOb047/particlesOb047.v", W3C_CORPUS_REASONS.wildcard],
  ["msMeta/Particles_w3c.xml/particlesOb048/particlesOb048.v", W3C_CORPUS_REASONS.wildcard],
  [
    "msMeta/Particles_w3c.xml/particlesOb052/particlesOb052.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  ["msMeta/Particles_w3c.xml/particlesOb054/particlesOb054.v", W3C_CORPUS_REASONS.wildcard],
  ["msMeta/Particles_w3c.xml/particlesOb057/particlesOb057.v", W3C_CORPUS_REASONS.wildcard],
  ["msMeta/Particles_w3c.xml/particlesOb059/particlesOb059.v", W3C_CORPUS_REASONS.wildcard],
  ["msMeta/Particles_w3c.xml/particlesOb060/particlesOb060.v", W3C_CORPUS_REASONS.wildcard],
  [
    "msMeta/Particles_w3c.xml/particlesQ013/particlesQ013.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/Particles_w3c.xml/particlesQ017/particlesQ017.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  ["msMeta/Particles_w3c.xml/particlesQ024/particlesQ024.v", W3C_CORPUS_REASONS.needsTriage],
  [
    "msMeta/Particles_w3c.xml/particlesQ030/particlesQ030.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/Particles_w3c.xml/particlesQ032/particlesQ032.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/Particles_w3c.xml/particlesR016/particlesR016.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/Particles_w3c.xml/particlesR022/particlesR022.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/Particles_w3c.xml/particlesV003/particlesV003.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/Particles_w3c.xml/particlesZ003/particlesZ003.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  ["msMeta/Particles_w3c.xml/particlesZ005/particlesZ005.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/Particles_w3c.xml/particlesZ012/particlesZ012.v", W3C_CORPUS_REASONS.needsTriage],
  [
    "msMeta/Particles_w3c.xml/particlesZ034_a1/particlesZ034_a1.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/Regex_w3c.xml/AlphabeticPresentationForms/AlphabeticPresentationForms.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  ["msMeta/Regex_w3c.xml/Arabic/Arabic.v", W3C_CORPUS_REASONS.patternOnNonString],
  [
    "msMeta/Regex_w3c.xml/ArabicPresentationForms-A/ArabicPresentationForms-A.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  ["msMeta/Regex_w3c.xml/Armenian/Armenian.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/Arrows/Arrows.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/BasicLatin/BasicLatin.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/Bengali/Bengali.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/BlockElements/BlockElements.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/Bopomofo/Bopomofo.v", W3C_CORPUS_REASONS.patternOnNonString],
  [
    "msMeta/Regex_w3c.xml/BopomofoExtended/BopomofoExtended.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  ["msMeta/Regex_w3c.xml/BoxDrawing/BoxDrawing.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/BraillePatterns/BraillePatterns.v", W3C_CORPUS_REASONS.patternOnNonString],
  [
    "msMeta/Regex_w3c.xml/CJKCompatibility/CJKCompatibility.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  [
    "msMeta/Regex_w3c.xml/CJKCompatibilityForms/CJKCompatibilityForms.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  [
    "msMeta/Regex_w3c.xml/CJKCompatibilityIdeographs/CJKCompatibilityIdeographs.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  [
    "msMeta/Regex_w3c.xml/CJKRadicalsSupplement/CJKRadicalsSupplement.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  [
    "msMeta/Regex_w3c.xml/CJKSymbolsandPunctuation/CJKSymbolsandPunctuation.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  [
    "msMeta/Regex_w3c.xml/CJKUnifiedIdeographs/CJKUnifiedIdeographs.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  ["msMeta/Regex_w3c.xml/Cherokee/Cherokee.v", W3C_CORPUS_REASONS.patternOnNonString],
  [
    "msMeta/Regex_w3c.xml/CombiningDiacriticalMarks/CombiningDiacriticalMarks.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  [
    "msMeta/Regex_w3c.xml/CombiningHalfMarks/CombiningHalfMarks.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  ["msMeta/Regex_w3c.xml/ControlPictures/ControlPictures.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/CurrencySymbols/CurrencySymbols.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/Cyrillic/Cyrillic.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/Devanagari/Devanagari.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/Dingbats/Dingbats.v", W3C_CORPUS_REASONS.patternOnNonString],
  [
    "msMeta/Regex_w3c.xml/EnclosedAlphanumerics/EnclosedAlphanumerics.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  [
    "msMeta/Regex_w3c.xml/EnclosedCJKLettersandMonths/EnclosedCJKLettersandMonths.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  ["msMeta/Regex_w3c.xml/Ethiopic/Ethiopic.v", W3C_CORPUS_REASONS.patternOnNonString],
  [
    "msMeta/Regex_w3c.xml/GeneralPunctuation/GeneralPunctuation.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  ["msMeta/Regex_w3c.xml/GeometricShapes/GeometricShapes.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/Georgian/Georgian.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/GreekExtended/GreekExtended.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/Gujarati/Gujarati.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/Gurmukhi/Gurmukhi.v", W3C_CORPUS_REASONS.patternOnNonString],
  [
    "msMeta/Regex_w3c.xml/HalfwidthandFullwidthForms/HalfwidthandFullwidthForms.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  [
    "msMeta/Regex_w3c.xml/HangulCompatibilityJamo/HangulCompatibilityJamo.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  ["msMeta/Regex_w3c.xml/HangulJamo/HangulJamo.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/Hebrew/Hebrew.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/Hiragana/Hiragana.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/IPAExtensions/IPAExtensions.v", W3C_CORPUS_REASONS.patternOnNonString],
  [
    "msMeta/Regex_w3c.xml/IdeographicDescriptionCharacters/IdeographicDescriptionCharacters.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  ["msMeta/Regex_w3c.xml/Kanbun/Kanbun.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/KangxiRadicals/KangxiRadicals.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/Kannada/Kannada.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/Katakana/Katakana.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/Khmer/Khmer.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/Lao/Lao.v", W3C_CORPUS_REASONS.patternOnNonString],
  [
    "msMeta/Regex_w3c.xml/Latin-1Supplement/Latin-1Supplement.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  ["msMeta/Regex_w3c.xml/LatinExtended-A/LatinExtended-A.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/LatinExtended-B/LatinExtended-B.v", W3C_CORPUS_REASONS.patternOnNonString],
  [
    "msMeta/Regex_w3c.xml/LatinExtendedAdditional/LatinExtendedAdditional.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  [
    "msMeta/Regex_w3c.xml/LetterlikeSymbols/LetterlikeSymbols.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  ["msMeta/Regex_w3c.xml/Malayalam/Malayalam.v", W3C_CORPUS_REASONS.patternOnNonString],
  [
    "msMeta/Regex_w3c.xml/MathematicalOperators/MathematicalOperators.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  [
    "msMeta/Regex_w3c.xml/MiscellaneousSymbols/MiscellaneousSymbols.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  [
    "msMeta/Regex_w3c.xml/MiscellaneousTechnical/MiscellaneousTechnical.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  ["msMeta/Regex_w3c.xml/Mongolian/Mongolian.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/Myanmar/Myanmar.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/NumberForms/NumberForms.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/Ogham/Ogham.v", W3C_CORPUS_REASONS.patternOnNonString],
  [
    "msMeta/Regex_w3c.xml/OpticalCharacterRecognition/OpticalCharacterRecognition.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  ["msMeta/Regex_w3c.xml/Oriya/Oriya.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/RegexTest_42/RegexTest_42.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/RegexTest_73/RegexTest_73.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/Runic/Runic.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/Sinhala/Sinhala.v", W3C_CORPUS_REASONS.patternOnNonString],
  [
    "msMeta/Regex_w3c.xml/SmallFormVariants/SmallFormVariants.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  [
    "msMeta/Regex_w3c.xml/SpacingModifierLetters/SpacingModifierLetters.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  ["msMeta/Regex_w3c.xml/Specials/Specials.v", W3C_CORPUS_REASONS.patternOnNonString],
  [
    "msMeta/Regex_w3c.xml/SuperscriptsandSubscripts/SuperscriptsandSubscripts.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  ["msMeta/Regex_w3c.xml/Syriac/Syriac.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/Tamil/Tamil.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/Telugu/Telugu.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/Thaana/Thaana.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/Thai/Thai.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/Tibetan/Tibetan.v", W3C_CORPUS_REASONS.patternOnNonString],
  [
    "msMeta/Regex_w3c.xml/UnifiedCanadianAboriginalSyllabics/UnifiedCanadianAboriginalSyllabics.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  ["msMeta/Regex_w3c.xml/YiRadicals/YiRadicals.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/YiSyllables/YiSyllables.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/p16/p16.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/p17/p17.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/p20/p20.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reDC5/reDC5.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reDF1/reDF1.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reDF2/reDF2.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reF43/reF43.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reG11/reG11.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reG13/reG13.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reI29/reI29.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reI31/reI31.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reI55/reI55.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Regex_w3c.xml/reI65/reI65.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Regex_w3c.xml/reI67/reI67.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Regex_w3c.xml/reI72/reI72.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/Regex_w3c.xml/reJ53/reJ53.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reJ55/reJ55.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reJ57/reJ57.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reJ59/reJ59.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reJ73/reJ73.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reK4/reK4.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Regex_w3c.xml/reL1/reL1.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL10/reL10.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL11/reL11.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL12/reL12.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL13/reL13.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL14/reL14.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL15/reL15.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL16/reL16.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL17/reL17.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL18/reL18.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL19/reL19.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL2/reL2.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL20/reL20.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL21/reL21.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL22/reL22.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL23/reL23.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL24/reL24.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL25/reL25.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL26/reL26.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL27/reL27.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL28/reL28.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL29/reL29.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL3/reL3.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL30/reL30.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL31/reL31.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL32/reL32.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL33/reL33.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL34/reL34.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL35/reL35.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL36/reL36.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL37/reL37.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL38/reL38.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL39/reL39.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL4/reL4.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL40/reL40.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL41/reL41.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL42/reL42.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL43/reL43.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL44/reL44.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL45/reL45.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL46/reL46.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL47/reL47.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL48/reL48.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL49/reL49.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL5/reL5.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL50/reL50.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL51/reL51.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL52/reL52.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL53/reL53.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL54/reL54.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL55/reL55.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL56/reL56.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL57/reL57.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL58/reL58.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL59/reL59.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL6/reL6.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL60/reL60.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL61/reL61.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL62/reL62.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL63/reL63.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL64/reL64.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL65/reL65.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL66/reL66.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL67/reL67.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL68/reL68.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL69/reL69.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL70/reL70.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL71/reL71.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL72/reL72.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL73/reL73.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL74/reL74.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL78/reL78.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL79/reL79.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL80/reL80.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL81/reL81.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL82/reL82.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL83/reL83.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL84/reL84.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL85/reL85.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL87/reL87.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL88/reL88.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reO2/reO2.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reP2/reP2.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reP27/reP27.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/Regex_w3c.xml/reP3/reP3.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/Regex_w3c.xml/reP4/reP4.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reQ18/reQ18.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reQ19/reQ19.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reQ20/reQ20.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reR20/reR20.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reR21/reR21.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reR22/reR22.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reR9/reR9.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reZ003v/reZ003v.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reZ006i/reZ006i.i", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/SimpleType_w3c.xml/stE065/stE065.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/SimpleType_w3c.xml/stE066/stE066.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/SimpleType_w3c.xml/stE079/stE079.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/SimpleType_w3c.xml/stE094/stE094.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/SimpleType_w3c.xml/stZ046/stZ046.v", W3C_CORPUS_REASONS.requiredArrayEmpty],
  ["msMeta/SimpleType_w3c.xml/stZ054/stZ054.v", W3C_CORPUS_REASONS.anyTypeContent],
  ["msMeta/SimpleType_w3c.xml/stZ072/stZ072.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/Wildcards_w3c.xml/wildG016/wildG016.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildG018/wildG018.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildG026/wildG026.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildG035/wildG035.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildG037/wildG037.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildI005/wildI005.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildI006/wildI006.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildO002/wildO002.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildO004/wildO004.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildO010/wildO010.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildO013/wildO013.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildO016/wildO016.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildO018/wildO018.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildO019/wildO019.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildO026/wildO026.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildO029/wildO029.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildO033/wildO033.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildO037/wildO037.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildO040/wildO040.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildZ003/wildZ003.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-ID-pattern-1/NISTXML-SV-IV-atomic-ID-pattern-2-1",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-ID-pattern-1/NISTXML-SV-IV-atomic-ID-pattern-2-2",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-ID-pattern-1/NISTXML-SV-IV-atomic-ID-pattern-2-3",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-ID-pattern-1/NISTXML-SV-IV-atomic-ID-pattern-2-4",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-ID-pattern-1/NISTXML-SV-IV-atomic-ID-pattern-2-5",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-ID-pattern-2/NISTXML-SV-IV-atomic-ID-pattern-3-1",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-ID-pattern-2/NISTXML-SV-IV-atomic-ID-pattern-3-2",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-ID-pattern-2/NISTXML-SV-IV-atomic-ID-pattern-3-3",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-ID-pattern-2/NISTXML-SV-IV-atomic-ID-pattern-3-4",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-ID-pattern-2/NISTXML-SV-IV-atomic-ID-pattern-3-5",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-ID-pattern-3/NISTXML-SV-IV-atomic-ID-pattern-4-1",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-ID-pattern-3/NISTXML-SV-IV-atomic-ID-pattern-4-2",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-ID-pattern-3/NISTXML-SV-IV-atomic-ID-pattern-4-3",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-ID-pattern-3/NISTXML-SV-IV-atomic-ID-pattern-4-4",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-ID-pattern-3/NISTXML-SV-IV-atomic-ID-pattern-4-5",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-ID-pattern-4/NISTXML-SV-IV-atomic-ID-pattern-5-1",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-ID-pattern-4/NISTXML-SV-IV-atomic-ID-pattern-5-2",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-ID-pattern-4/NISTXML-SV-IV-atomic-ID-pattern-5-3",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-ID-pattern-4/NISTXML-SV-IV-atomic-ID-pattern-5-4",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-ID-pattern-4/NISTXML-SV-IV-atomic-ID-pattern-5-5",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-ID-pattern/NISTXML-SV-IV-atomic-ID-pattern-1-1",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-ID-pattern/NISTXML-SV-IV-atomic-ID-pattern-1-2",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-ID-pattern/NISTXML-SV-IV-atomic-ID-pattern-1-3",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-ID-pattern/NISTXML-SV-IV-atomic-ID-pattern-1-4",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-ID-pattern/NISTXML-SV-IV-atomic-ID-pattern-1-5",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-NCName-pattern-1/NISTXML-SV-IV-atomic-NCName-pattern-2-1",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-NCName-pattern-1/NISTXML-SV-IV-atomic-NCName-pattern-2-2",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-NCName-pattern-1/NISTXML-SV-IV-atomic-NCName-pattern-2-3",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-NCName-pattern-1/NISTXML-SV-IV-atomic-NCName-pattern-2-4",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-NCName-pattern-1/NISTXML-SV-IV-atomic-NCName-pattern-2-5",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-NCName-pattern-2/NISTXML-SV-IV-atomic-NCName-pattern-3-1",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-NCName-pattern-2/NISTXML-SV-IV-atomic-NCName-pattern-3-2",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-NCName-pattern-2/NISTXML-SV-IV-atomic-NCName-pattern-3-3",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-NCName-pattern-2/NISTXML-SV-IV-atomic-NCName-pattern-3-4",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-NCName-pattern-2/NISTXML-SV-IV-atomic-NCName-pattern-3-5",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-NCName-pattern-3/NISTXML-SV-IV-atomic-NCName-pattern-4-1",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-NCName-pattern-3/NISTXML-SV-IV-atomic-NCName-pattern-4-2",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-NCName-pattern-3/NISTXML-SV-IV-atomic-NCName-pattern-4-3",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-NCName-pattern-3/NISTXML-SV-IV-atomic-NCName-pattern-4-4",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-NCName-pattern-3/NISTXML-SV-IV-atomic-NCName-pattern-4-5",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-NCName-pattern-4/NISTXML-SV-IV-atomic-NCName-pattern-5-1",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-NCName-pattern-4/NISTXML-SV-IV-atomic-NCName-pattern-5-2",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-NCName-pattern-4/NISTXML-SV-IV-atomic-NCName-pattern-5-3",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-NCName-pattern-4/NISTXML-SV-IV-atomic-NCName-pattern-5-4",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-NCName-pattern-4/NISTXML-SV-IV-atomic-NCName-pattern-5-5",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-NCName-pattern/NISTXML-SV-IV-atomic-NCName-pattern-1-1",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-NCName-pattern/NISTXML-SV-IV-atomic-NCName-pattern-1-2",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-NCName-pattern/NISTXML-SV-IV-atomic-NCName-pattern-1-3",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-NCName-pattern/NISTXML-SV-IV-atomic-NCName-pattern-1-4",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-NCName-pattern/NISTXML-SV-IV-atomic-NCName-pattern-1-5",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-QName-pattern-1/NISTXML-SV-IV-atomic-QName-pattern-2-1",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-QName-pattern-1/NISTXML-SV-IV-atomic-QName-pattern-2-2",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-QName-pattern-1/NISTXML-SV-IV-atomic-QName-pattern-2-3",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-QName-pattern-1/NISTXML-SV-IV-atomic-QName-pattern-2-4",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-QName-pattern-1/NISTXML-SV-IV-atomic-QName-pattern-2-5",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-QName-pattern-2/NISTXML-SV-IV-atomic-QName-pattern-3-1",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-QName-pattern-2/NISTXML-SV-IV-atomic-QName-pattern-3-2",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-QName-pattern-2/NISTXML-SV-IV-atomic-QName-pattern-3-3",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-QName-pattern-2/NISTXML-SV-IV-atomic-QName-pattern-3-4",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-QName-pattern-2/NISTXML-SV-IV-atomic-QName-pattern-3-5",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-QName-pattern-3/NISTXML-SV-IV-atomic-QName-pattern-4-1",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-QName-pattern-3/NISTXML-SV-IV-atomic-QName-pattern-4-2",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-QName-pattern-3/NISTXML-SV-IV-atomic-QName-pattern-4-3",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-QName-pattern-3/NISTXML-SV-IV-atomic-QName-pattern-4-4",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-QName-pattern-3/NISTXML-SV-IV-atomic-QName-pattern-4-5",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-QName-pattern-4/NISTXML-SV-IV-atomic-QName-pattern-5-1",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-QName-pattern-4/NISTXML-SV-IV-atomic-QName-pattern-5-2",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-QName-pattern-4/NISTXML-SV-IV-atomic-QName-pattern-5-3",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-QName-pattern-4/NISTXML-SV-IV-atomic-QName-pattern-5-4",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-QName-pattern-4/NISTXML-SV-IV-atomic-QName-pattern-5-5",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-QName-pattern/NISTXML-SV-IV-atomic-QName-pattern-1-1",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-QName-pattern/NISTXML-SV-IV-atomic-QName-pattern-1-2",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-QName-pattern/NISTXML-SV-IV-atomic-QName-pattern-1-3",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-QName-pattern/NISTXML-SV-IV-atomic-QName-pattern-1-4",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-QName-pattern/NISTXML-SV-IV-atomic-QName-pattern-1-5",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-normalizedString-length/NISTXML-SV-IV-atomic-normalizedString-length-1-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-normalizedString-length/NISTXML-SV-IV-atomic-normalizedString-length-1-2",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-normalizedString-length/NISTXML-SV-IV-atomic-normalizedString-length-1-3",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-normalizedString-length/NISTXML-SV-IV-atomic-normalizedString-length-1-4",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-normalizedString-length/NISTXML-SV-IV-atomic-normalizedString-length-1-5",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-normalizedString-maxLength-1/NISTXML-SV-IV-atomic-normalizedString-maxLength-2-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-normalizedString-maxLength-2/NISTXML-SV-IV-atomic-normalizedString-maxLength-3-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-normalizedString-maxLength-3/NISTXML-SV-IV-atomic-normalizedString-maxLength-4-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-normalizedString-maxLength-4/NISTXML-SV-IV-atomic-normalizedString-maxLength-5-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-normalizedString-maxLength/NISTXML-SV-IV-atomic-normalizedString-maxLength-1-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-normalizedString-maxLength/NISTXML-SV-IV-atomic-normalizedString-maxLength-1-2",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-normalizedString-maxLength/NISTXML-SV-IV-atomic-normalizedString-maxLength-1-3",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-normalizedString-maxLength/NISTXML-SV-IV-atomic-normalizedString-maxLength-1-4",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-normalizedString-maxLength/NISTXML-SV-IV-atomic-normalizedString-maxLength-1-5",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-normalizedString-minLength/NISTXML-SV-IV-atomic-normalizedString-minLength-1-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-string-length/NISTXML-SV-IV-atomic-string-length-1-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-string-length/NISTXML-SV-IV-atomic-string-length-1-2",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-string-length/NISTXML-SV-IV-atomic-string-length-1-3",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-string-length/NISTXML-SV-IV-atomic-string-length-1-4",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-string-length/NISTXML-SV-IV-atomic-string-length-1-5",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-string-maxLength-1/NISTXML-SV-IV-atomic-string-maxLength-2-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-string-maxLength-2/NISTXML-SV-IV-atomic-string-maxLength-3-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-string-maxLength-3/NISTXML-SV-IV-atomic-string-maxLength-4-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-string-maxLength-4/NISTXML-SV-IV-atomic-string-maxLength-5-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-string-maxLength/NISTXML-SV-IV-atomic-string-maxLength-1-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-string-maxLength/NISTXML-SV-IV-atomic-string-maxLength-1-2",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-string-maxLength/NISTXML-SV-IV-atomic-string-maxLength-1-3",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-string-maxLength/NISTXML-SV-IV-atomic-string-maxLength-1-4",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-string-maxLength/NISTXML-SV-IV-atomic-string-maxLength-1-5",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-string-minLength/NISTXML-SV-IV-atomic-string-minLength-1-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-token-length/NISTXML-SV-IV-atomic-token-length-1-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-token-length/NISTXML-SV-IV-atomic-token-length-1-2",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-token-length/NISTXML-SV-IV-atomic-token-length-1-3",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-token-length/NISTXML-SV-IV-atomic-token-length-1-4",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-token-length/NISTXML-SV-IV-atomic-token-length-1-5",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-token-maxLength-1/NISTXML-SV-IV-atomic-token-maxLength-2-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-token-maxLength-2/NISTXML-SV-IV-atomic-token-maxLength-3-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-token-maxLength-3/NISTXML-SV-IV-atomic-token-maxLength-4-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-token-maxLength-4/NISTXML-SV-IV-atomic-token-maxLength-5-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-token-maxLength/NISTXML-SV-IV-atomic-token-maxLength-1-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-token-maxLength/NISTXML-SV-IV-atomic-token-maxLength-1-2",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-token-maxLength/NISTXML-SV-IV-atomic-token-maxLength-1-3",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-token-maxLength/NISTXML-SV-IV-atomic-token-maxLength-1-4",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-token-maxLength/NISTXML-SV-IV-atomic-token-maxLength-1-5",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-token-minLength/NISTXML-SV-IV-atomic-token-minLength-1-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-NCName-pattern-1/NISTXML-SV-IV-list-NCName-pattern-2-1",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-NCName-pattern-1/NISTXML-SV-IV-list-NCName-pattern-2-2",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-NCName-pattern-1/NISTXML-SV-IV-list-NCName-pattern-2-3",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-NCName-pattern-1/NISTXML-SV-IV-list-NCName-pattern-2-4",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-NCName-pattern-1/NISTXML-SV-IV-list-NCName-pattern-2-5",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-NCName-pattern-2/NISTXML-SV-IV-list-NCName-pattern-3-1",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-NCName-pattern-2/NISTXML-SV-IV-list-NCName-pattern-3-2",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-NCName-pattern-2/NISTXML-SV-IV-list-NCName-pattern-3-3",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-NCName-pattern-2/NISTXML-SV-IV-list-NCName-pattern-3-4",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-NCName-pattern-2/NISTXML-SV-IV-list-NCName-pattern-3-5",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-NCName-pattern-3/NISTXML-SV-IV-list-NCName-pattern-4-1",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-NCName-pattern-3/NISTXML-SV-IV-list-NCName-pattern-4-2",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-NCName-pattern-3/NISTXML-SV-IV-list-NCName-pattern-4-3",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-NCName-pattern-3/NISTXML-SV-IV-list-NCName-pattern-4-4",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-NCName-pattern-3/NISTXML-SV-IV-list-NCName-pattern-4-5",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-NCName-pattern-4/NISTXML-SV-IV-list-NCName-pattern-5-1",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-NCName-pattern-4/NISTXML-SV-IV-list-NCName-pattern-5-2",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-NCName-pattern-4/NISTXML-SV-IV-list-NCName-pattern-5-3",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-NCName-pattern-4/NISTXML-SV-IV-list-NCName-pattern-5-4",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-NCName-pattern-4/NISTXML-SV-IV-list-NCName-pattern-5-5",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-NCName-pattern/NISTXML-SV-IV-list-NCName-pattern-1-1",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-NCName-pattern/NISTXML-SV-IV-list-NCName-pattern-1-2",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-NCName-pattern/NISTXML-SV-IV-list-NCName-pattern-1-3",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-NCName-pattern/NISTXML-SV-IV-list-NCName-pattern-1-4",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-NCName-pattern/NISTXML-SV-IV-list-NCName-pattern-1-5",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-QName-pattern-1/NISTXML-SV-IV-list-QName-pattern-2-1",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-QName-pattern-1/NISTXML-SV-IV-list-QName-pattern-2-2",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-QName-pattern-1/NISTXML-SV-IV-list-QName-pattern-2-3",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-QName-pattern-1/NISTXML-SV-IV-list-QName-pattern-2-4",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-QName-pattern-1/NISTXML-SV-IV-list-QName-pattern-2-5",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-QName-pattern-2/NISTXML-SV-IV-list-QName-pattern-3-1",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-QName-pattern-2/NISTXML-SV-IV-list-QName-pattern-3-2",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-QName-pattern-2/NISTXML-SV-IV-list-QName-pattern-3-3",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-QName-pattern-2/NISTXML-SV-IV-list-QName-pattern-3-4",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-QName-pattern-2/NISTXML-SV-IV-list-QName-pattern-3-5",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-QName-pattern-3/NISTXML-SV-IV-list-QName-pattern-4-1",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-QName-pattern-3/NISTXML-SV-IV-list-QName-pattern-4-2",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-QName-pattern-3/NISTXML-SV-IV-list-QName-pattern-4-3",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-QName-pattern-3/NISTXML-SV-IV-list-QName-pattern-4-4",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-QName-pattern-3/NISTXML-SV-IV-list-QName-pattern-4-5",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-QName-pattern-4/NISTXML-SV-IV-list-QName-pattern-5-1",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-QName-pattern-4/NISTXML-SV-IV-list-QName-pattern-5-2",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-QName-pattern-4/NISTXML-SV-IV-list-QName-pattern-5-3",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-QName-pattern-4/NISTXML-SV-IV-list-QName-pattern-5-4",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-QName-pattern-4/NISTXML-SV-IV-list-QName-pattern-5-5",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-QName-pattern/NISTXML-SV-IV-list-QName-pattern-1-1",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-QName-pattern/NISTXML-SV-IV-list-QName-pattern-1-2",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-QName-pattern/NISTXML-SV-IV-list-QName-pattern-1-3",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-QName-pattern/NISTXML-SV-IV-list-QName-pattern-1-4",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/list-QName-pattern/NISTXML-SV-IV-list-QName-pattern-1-5",
    W3C_CORPUS_REASONS.regexTranslation,
  ],
  ["sunMeta/CType.testSet/basetd00101m1/Positive", W3C_CORPUS_REASONS.simpleContentShape],
  ["sunMeta/CType.testSet/basetd00101m2/Positive", W3C_CORPUS_REASONS.simpleContentShape],
  ["sunMeta/CType.testSet/targetns00101m/targetNS00101m1_p", W3C_CORPUS_REASONS.needsTriage],
  [
    "sunMeta/ElemDecl.testSet/abstract00101m/abstract00101m1_p",
    W3C_CORPUS_REASONS.requiredArrayEmpty,
  ],
  [
    "sunMeta/ElemDecl.testSet/disallowedsubst00301m1/Positive",
    W3C_CORPUS_REASONS.substitutionGroups,
  ],
  [
    "sunMeta/ElemDecl.testSet/disallowedsubst00401m1/Positive",
    W3C_CORPUS_REASONS.substitutionGroups,
  ],
  [
    "sunMeta/ElemDecl.testSet/disallowedsubst00501m1/Positive",
    W3C_CORPUS_REASONS.substitutionGroups,
  ],
  [
    "sunMeta/ElemDecl.testSet/disallowedsubst00502m1/Positive",
    W3C_CORPUS_REASONS.substitutionGroups,
  ],
  [
    "sunMeta/ElemDecl.testSet/disallowedsubst00502m2/Positive",
    W3C_CORPUS_REASONS.substitutionGroups,
  ],
  [
    "sunMeta/ElemDecl.testSet/disallowedsubst00503m1/Positive",
    W3C_CORPUS_REASONS.substitutionGroups,
  ],
  [
    "sunMeta/ElemDecl.testSet/disallowedsubst00503m2/Positive",
    W3C_CORPUS_REASONS.substitutionGroups,
  ],
  [
    "sunMeta/ElemDecl.testSet/substgrpaffil00101m/substGrpAffil00101m1_p",
    W3C_CORPUS_REASONS.requiredArrayEmpty,
  ],
  ["sunMeta/ElemDecl.testSet/targetns00101m/targetNS00101m1_p", W3C_CORPUS_REASONS.needsTriage],
  ["sunMeta/ElemDecl.testSet/typedef00205m/typeDef00205m1_p", W3C_CORPUS_REASONS.anyTypeContent],
  ["sunMeta/ElemDecl.testSet/typedef01301m1/Positive", W3C_CORPUS_REASONS.anyTypeContent],
  [
    "sunMeta/ElemDecl.testSet/valueconstraint00501m1/Positive",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  [
    "sunMeta/ElemDecl.testSet/valueconstraint00501m2/Positive",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  [
    "sunMeta/ElemDecl.testSet/valueconstraint00501m4/Positive",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  [
    "sunMeta/ElemDecl.testSet/valueconstraint00501m5/Positive",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  [
    "sunMeta/ElemDecl.testSet/valueconstraint00601m7/Positive",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  ["sunMeta/MGroup.testSet/compositor00202m1/Positive", W3C_CORPUS_REASONS.undefinedValue],
  ["sunMeta/MGroup.testSet/particles00203m1/Positive", W3C_CORPUS_REASONS.undefinedValue],
  ["sunMeta/SType.testSet/st_name00401m/ST_name00401m1_p", W3C_CORPUS_REASONS.needsTriage],
  ["sunMeta/SType.testSet/st_targetns00101m/ST_targetNS00101m1_p", W3C_CORPUS_REASONS.needsTriage],
  ["sunMeta/SType.testSet/st_targetns00101m/ST_targetNS00101m2_p", W3C_CORPUS_REASONS.needsTriage],
  ["sunMeta/SType.testSet/st_targetns00201m/ST_targetNS00201m1_p", W3C_CORPUS_REASONS.needsTriage],
  ["sunMeta/suntest.testSet/xsd001/xsd001.v00", W3C_CORPUS_REASONS.needsTriage],
  ["sunMeta/suntest.testSet/xsd001/xsd001.v01", W3C_CORPUS_REASONS.needsTriage],
  ["sunMeta/suntest.testSet/xsd001/xsd001.v02", W3C_CORPUS_REASONS.needsTriage],
  ["sunMeta/suntest.testSet/xsd001/xsd001.v03", W3C_CORPUS_REASONS.needsTriage],
  ["sunMeta/suntest.testSet/xsd008/xsd008.v00", W3C_CORPUS_REASONS.requiredArrayEmpty],
  ["boeingMeta/BoeingXSDTestSet.testSet/ipo6/ipo_1", W3C_CORPUS_REASONS.substitutionGroups],
]);
