// Known failures for the full-corpus suite (#108 Phase 4), keyed by
// `<testSet-relative-path>/<testGroup>/<instanceTest>`. Entries run as
// `it.fails` — a fix that makes a case pass turns the suite red; remove the
// entry in the same PR. Generated from full corpus runs, then hand-maintained.
export const W3C_CORPUS_REASONS = {
  choiceDocumentOrder:
    "choice: interleaved repeated branches collapse into per-element arrays; document order is lost and the serialized XML no longer validates",
  libxmlRejectsSerialized: "libxml2 rejects serialized XML (needs triage)",
  wildcard: "unsupported: xs:any wildcard content",
  strictWildcardHarness:
    "strict wildcard: extras re-serialized faithfully, but single-schema libxml2 validation cannot see cross-file declarations (harness limitation)",
  needsTriage: "needs triage",
  undefinedValue: "parse: element value arrives as undefined (needs triage)",
  requiredArrayEmpty: "cardinality: required element array parsed empty (needs triage)",
  patternOnNonString:
    "runtime: pattern checked against coerced value, not the original lexical (lexical preservation needed)",
  simpleContentShape: "parse: simpleContent _text shape mismatch (needs triage)",
} as const;

export const W3C_CORPUS_KNOWN_FAILURES = new Map<string, string>([
  // Substitution groups themselves work (salutation substitutes
  // ipo:ExternFirstElement); what fails is the group-in-choice ordering:
  // shipTo/billTo/singleAddress are emitted after comment/items.
  ["boeingMeta/BoeingXSDTestSet.testSet/ipo6/ipo_2", W3C_CORPUS_REASONS.choiceDocumentOrder],
  ["msMeta/Additional_w3c.xml/addB012/addB012.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Additional_w3c.xml/addB067/addB067.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Additional_w3c.xml/addB068/addB068.i", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Additional_w3c.xml/addB090/addB090.v", W3C_CORPUS_REASONS.wildcard],
  ["msMeta/Additional_w3c.xml/addB116/addB116.v", W3C_CORPUS_REASONS.strictWildcardHarness],
  ["msMeta/Additional_w3c.xml/addB135/addB135.v", W3C_CORPUS_REASONS.wildcard],
  ["msMeta/Additional_w3c.xml/addB187/addB187.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/Additional_w3c.xml/addC001/addC001.v", W3C_CORPUS_REASONS.undefinedValue],
  ["msMeta/Additional_w3c.xml/isDefault072/isDefault072.v", W3C_CORPUS_REASONS.undefinedValue],
  [
    "msMeta/Additional_w3c.xml/isDefault078/isDefault078.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  ["msMeta/Additional_w3c.xml/isDefault079/isDefault079.v", W3C_CORPUS_REASONS.needsTriage],
  [
    "msMeta/Additional_w3c.xml/memberType004/memberType004.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/Additional_w3c.xml/memberType008/memberType008.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  ["msMeta/AttributeGroup_w3c.xml/attgD019/attgD019.v", W3C_CORPUS_REASONS.strictWildcardHarness],
  ["msMeta/AttributeGroup_w3c.xml/attgD020/attgD020.v", W3C_CORPUS_REASONS.strictWildcardHarness],
  ["msMeta/AttributeGroup_w3c.xml/attgD021/attgD021.v", W3C_CORPUS_REASONS.strictWildcardHarness],
  ["msMeta/AttributeGroup_w3c.xml/attgD022/attgD022.v", W3C_CORPUS_REASONS.strictWildcardHarness],
  ["msMeta/AttributeGroup_w3c.xml/attgD025/attgD025.v", W3C_CORPUS_REASONS.strictWildcardHarness],
  ["msMeta/AttributeGroup_w3c.xml/attgD034/attgD034.v", W3C_CORPUS_REASONS.strictWildcardHarness],
  ["msMeta/Attribute_w3c.xml/attO009/attO009.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/Attribute_w3c.xml/attO010/attO010.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/Attribute_w3c.xml/attO011/attO011.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/ComplexType_w3c.xml/ctA002/ctA002.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/ComplexType_w3c.xml/ctA003/ctA003.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/ComplexType_w3c.xml/ctL021/ctL021.v", W3C_CORPUS_REASONS.strictWildcardHarness],
  ["msMeta/ComplexType_w3c.xml/ctL022/ctL022.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/ComplexType_w3c.xml/ctZ007/ctZ007.v", W3C_CORPUS_REASONS.requiredArrayEmpty],
  [
    "msMeta/DataTypes_w3c.xml/QName006_2089/QName006_2089.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/DataTypes_w3c.xml/QName_enumeration002_1369/QName_enumeration002_1369.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/DataTypes_w3c.xml/QName_enumeration004_1371/QName_enumeration004_1371.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/DataTypes_w3c.xml/gMonth002_2061/gMonth002_2061.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/DataTypes_w3c.xml/gMonth004_2063/gMonth004_2063.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  ["msMeta/Element_w3c.xml/QFE1700c2/QFE1700c2.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/Errata10_w3c.xml/errC001/errC001.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/Group_w3c.xml/groupF009v/groupF009v.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Group_w3c.xml/groupH009v/groupH009v.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Group_w3c.xml/groupH014v/groupH014v.v", W3C_CORPUS_REASONS.choiceDocumentOrder],
  ["msMeta/Group_w3c.xml/groupH017v/groupH017v.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/Group_w3c.xml/groupH018v/groupH018v.v", W3C_CORPUS_REASONS.choiceDocumentOrder],
  ["msMeta/Group_w3c.xml/groupJ009v/groupJ009v.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Group_w3c.xml/groupL009v/groupL009v.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Group_w3c.xml/groupN009v/groupN009v.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/IdentityConstraint_w3c.xml/idF012/idF012.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/IdentityConstraint_w3c.xml/idF013/idF013.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/IdentityConstraint_w3c.xml/idF014/idF014.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/IdentityConstraint_w3c.xml/idG030/idG030.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/ModelGroups_w3c.xml/mgA015/mgA015.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/ModelGroups_w3c.xml/mgF010/mgF010.v", W3C_CORPUS_REASONS.wildcard],
  ["msMeta/ModelGroups_w3c.xml/mgF011/mgF011.v", W3C_CORPUS_REASONS.wildcard],
  ["msMeta/ModelGroups_w3c.xml/mgF012/mgF012.v", W3C_CORPUS_REASONS.wildcard],
  ["msMeta/ModelGroups_w3c.xml/mgF014/mgF014.v", W3C_CORPUS_REASONS.wildcard],
  ["msMeta/ModelGroups_w3c.xml/mgF019/mgF019.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/ModelGroups_w3c.xml/mgI010/mgI010.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/ModelGroups_w3c.xml/mgI011/mgI011.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/ModelGroups_w3c.xml/mgI013/mgI013.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/ModelGroups_w3c.xml/mgO006/mgO006.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/ModelGroups_w3c.xml/mgQ002/mgQ002.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/ModelGroups_w3c.xml/mgQ003/mgQ003.v", W3C_CORPUS_REASONS.choiceDocumentOrder],
  ["msMeta/Notations_w3c.xml/notatH001v/notatH001v.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  [
    "msMeta/Particles_w3c.xml/particlesA006/particlesA006.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/Particles_w3c.xml/particlesA007/particlesA007.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  ["msMeta/Particles_w3c.xml/particlesB013/particlesB013.v", W3C_CORPUS_REASONS.wildcard],
  [
    "msMeta/Particles_w3c.xml/particlesEb027/particlesEb027.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/Particles_w3c.xml/particlesEb036/particlesEb036.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/Particles_w3c.xml/particlesEb038/particlesEb038.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/Particles_w3c.xml/particlesJs001/particlesJs001.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  ["msMeta/Particles_w3c.xml/particlesOb003/particlesOb003.v", W3C_CORPUS_REASONS.wildcard],
  ["msMeta/Particles_w3c.xml/particlesOb006/particlesOb006.v", W3C_CORPUS_REASONS.wildcard],
  ["msMeta/Particles_w3c.xml/particlesOb007/particlesOb007.v", W3C_CORPUS_REASONS.wildcard],
  ["msMeta/Particles_w3c.xml/particlesOb012/particlesOb012.v", W3C_CORPUS_REASONS.wildcard],
  ["msMeta/Particles_w3c.xml/particlesOb015/particlesOb015.v", W3C_CORPUS_REASONS.wildcard],
  [
    "msMeta/Particles_w3c.xml/particlesOb022/particlesOb022.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/Particles_w3c.xml/particlesOb042/particlesOb042.v",
    W3C_CORPUS_REASONS.strictWildcardHarness,
  ],
  ["msMeta/Particles_w3c.xml/particlesOb047/particlesOb047.v", W3C_CORPUS_REASONS.wildcard],
  ["msMeta/Particles_w3c.xml/particlesOb048/particlesOb048.v", W3C_CORPUS_REASONS.wildcard],
  [
    "msMeta/Particles_w3c.xml/particlesOb052/particlesOb052.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  ["msMeta/Particles_w3c.xml/particlesOb054/particlesOb054.v", W3C_CORPUS_REASONS.wildcard],
  ["msMeta/Particles_w3c.xml/particlesOb057/particlesOb057.v", W3C_CORPUS_REASONS.wildcard],
  ["msMeta/Particles_w3c.xml/particlesOb059/particlesOb059.v", W3C_CORPUS_REASONS.wildcard],
  ["msMeta/Particles_w3c.xml/particlesOb060/particlesOb060.v", W3C_CORPUS_REASONS.wildcard],
  [
    "msMeta/Particles_w3c.xml/particlesQ013/particlesQ013.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/Particles_w3c.xml/particlesQ017/particlesQ017.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  ["msMeta/Particles_w3c.xml/particlesQ024/particlesQ024.v", W3C_CORPUS_REASONS.needsTriage],
  [
    "msMeta/Particles_w3c.xml/particlesQ030/particlesQ030.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/Particles_w3c.xml/particlesQ032/particlesQ032.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/Particles_w3c.xml/particlesR016/particlesR016.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/Particles_w3c.xml/particlesR022/particlesR022.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/Particles_w3c.xml/particlesV003/particlesV003.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/Particles_w3c.xml/particlesZ003/particlesZ003.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  ["msMeta/Particles_w3c.xml/particlesZ005/particlesZ005.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/Particles_w3c.xml/particlesZ012/particlesZ012.v", W3C_CORPUS_REASONS.needsTriage],
  [
    "msMeta/Particles_w3c.xml/particlesZ034_a1/particlesZ034_a1.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/Regex_w3c.xml/ArabicPresentationForms-A/ArabicPresentationForms-A.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  ["msMeta/Regex_w3c.xml/BasicLatin/BasicLatin.v", W3C_CORPUS_REASONS.patternOnNonString],
  [
    "msMeta/Regex_w3c.xml/Latin-1Supplement/Latin-1Supplement.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  ["msMeta/Regex_w3c.xml/LatinExtended-A/LatinExtended-A.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/LatinExtended-B/LatinExtended-B.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/RegexTest_42/RegexTest_42.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/RegexTest_73/RegexTest_73.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/p16/p16.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/p17/p17.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/p20/p20.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reDC5/reDC5.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reDF1/reDF1.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reDF2/reDF2.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reF43/reF43.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reG11/reG11.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reG13/reG13.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reI29/reI29.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reI31/reI31.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reI55/reI55.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Regex_w3c.xml/reI65/reI65.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Regex_w3c.xml/reI67/reI67.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Regex_w3c.xml/reI72/reI72.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/Regex_w3c.xml/reJ53/reJ53.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reJ55/reJ55.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reJ57/reJ57.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reJ59/reJ59.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reJ73/reJ73.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reK4/reK4.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Regex_w3c.xml/reL2/reL2.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL3/reL3.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL4/reL4.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL81/reL81.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL85/reL85.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reO2/reO2.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reP2/reP2.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reP27/reP27.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/Regex_w3c.xml/reP3/reP3.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/Regex_w3c.xml/reP4/reP4.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reQ18/reQ18.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reQ19/reQ19.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reQ20/reQ20.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reR20/reR20.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reR21/reR21.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reR22/reR22.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reR9/reR9.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reZ006i/reZ006i.i", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/SimpleType_w3c.xml/stE065/stE065.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/SimpleType_w3c.xml/stE066/stE066.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/SimpleType_w3c.xml/stE079/stE079.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/SimpleType_w3c.xml/stE094/stE094.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/SimpleType_w3c.xml/stZ072/stZ072.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/Wildcards_w3c.xml/wildG016/wildG016.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildG018/wildG018.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildG026/wildG026.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildG035/wildG035.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildG037/wildG037.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildI005/wildI005.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildI006/wildI006.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildO002/wildO002.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildO004/wildO004.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildO010/wildO010.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildO013/wildO013.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildO016/wildO016.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildO018/wildO018.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildO019/wildO019.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildO026/wildO026.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildO029/wildO029.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildO033/wildO033.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildO037/wildO037.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildO040/wildO040.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Wildcards_w3c.xml/wildZ003/wildZ003.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-normalizedString-length/NISTXML-SV-IV-atomic-normalizedString-length-1-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-normalizedString-length/NISTXML-SV-IV-atomic-normalizedString-length-1-2",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-normalizedString-length/NISTXML-SV-IV-atomic-normalizedString-length-1-3",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-normalizedString-length/NISTXML-SV-IV-atomic-normalizedString-length-1-4",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-normalizedString-length/NISTXML-SV-IV-atomic-normalizedString-length-1-5",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-normalizedString-maxLength-1/NISTXML-SV-IV-atomic-normalizedString-maxLength-2-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-normalizedString-maxLength-2/NISTXML-SV-IV-atomic-normalizedString-maxLength-3-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-normalizedString-maxLength-3/NISTXML-SV-IV-atomic-normalizedString-maxLength-4-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-normalizedString-maxLength-4/NISTXML-SV-IV-atomic-normalizedString-maxLength-5-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-normalizedString-maxLength/NISTXML-SV-IV-atomic-normalizedString-maxLength-1-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-normalizedString-maxLength/NISTXML-SV-IV-atomic-normalizedString-maxLength-1-2",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-normalizedString-maxLength/NISTXML-SV-IV-atomic-normalizedString-maxLength-1-3",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-normalizedString-maxLength/NISTXML-SV-IV-atomic-normalizedString-maxLength-1-4",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-normalizedString-maxLength/NISTXML-SV-IV-atomic-normalizedString-maxLength-1-5",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-normalizedString-minLength/NISTXML-SV-IV-atomic-normalizedString-minLength-1-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-string-length/NISTXML-SV-IV-atomic-string-length-1-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-string-length/NISTXML-SV-IV-atomic-string-length-1-2",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-string-length/NISTXML-SV-IV-atomic-string-length-1-3",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-string-length/NISTXML-SV-IV-atomic-string-length-1-4",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-string-length/NISTXML-SV-IV-atomic-string-length-1-5",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-string-maxLength-1/NISTXML-SV-IV-atomic-string-maxLength-2-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-string-maxLength-2/NISTXML-SV-IV-atomic-string-maxLength-3-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-string-maxLength-3/NISTXML-SV-IV-atomic-string-maxLength-4-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-string-maxLength-4/NISTXML-SV-IV-atomic-string-maxLength-5-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-string-maxLength/NISTXML-SV-IV-atomic-string-maxLength-1-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-string-maxLength/NISTXML-SV-IV-atomic-string-maxLength-1-2",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-string-maxLength/NISTXML-SV-IV-atomic-string-maxLength-1-3",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-string-maxLength/NISTXML-SV-IV-atomic-string-maxLength-1-4",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-string-maxLength/NISTXML-SV-IV-atomic-string-maxLength-1-5",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-string-minLength/NISTXML-SV-IV-atomic-string-minLength-1-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-token-length/NISTXML-SV-IV-atomic-token-length-1-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-token-length/NISTXML-SV-IV-atomic-token-length-1-2",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-token-length/NISTXML-SV-IV-atomic-token-length-1-3",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-token-length/NISTXML-SV-IV-atomic-token-length-1-4",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-token-length/NISTXML-SV-IV-atomic-token-length-1-5",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-token-maxLength-1/NISTXML-SV-IV-atomic-token-maxLength-2-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-token-maxLength-2/NISTXML-SV-IV-atomic-token-maxLength-3-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-token-maxLength-3/NISTXML-SV-IV-atomic-token-maxLength-4-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-token-maxLength-4/NISTXML-SV-IV-atomic-token-maxLength-5-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-token-maxLength/NISTXML-SV-IV-atomic-token-maxLength-1-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-token-maxLength/NISTXML-SV-IV-atomic-token-maxLength-1-2",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-token-maxLength/NISTXML-SV-IV-atomic-token-maxLength-1-3",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-token-maxLength/NISTXML-SV-IV-atomic-token-maxLength-1-4",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-token-maxLength/NISTXML-SV-IV-atomic-token-maxLength-1-5",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  [
    "nistMeta/NISTXMLSchemaDatatypes.testSet/atomic-token-minLength/NISTXML-SV-IV-atomic-token-minLength-1-1",
    W3C_CORPUS_REASONS.undefinedValue,
  ],
  ["sunMeta/CType.testSet/basetd00101m1/Positive", W3C_CORPUS_REASONS.simpleContentShape],
  ["sunMeta/CType.testSet/basetd00101m2/Positive", W3C_CORPUS_REASONS.simpleContentShape],
  ["sunMeta/CType.testSet/targetns00101m/targetNS00101m1_p", W3C_CORPUS_REASONS.needsTriage],
  ["sunMeta/ElemDecl.testSet/targetns00101m/targetNS00101m1_p", W3C_CORPUS_REASONS.needsTriage],
  [
    "sunMeta/ElemDecl.testSet/valueconstraint00501m1/Positive",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  [
    "sunMeta/ElemDecl.testSet/valueconstraint00501m2/Positive",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  [
    "sunMeta/ElemDecl.testSet/valueconstraint00501m4/Positive",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  [
    "sunMeta/ElemDecl.testSet/valueconstraint00501m5/Positive",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  [
    "sunMeta/ElemDecl.testSet/valueconstraint00601m7/Positive",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  ["sunMeta/MGroup.testSet/compositor00202m1/Positive", W3C_CORPUS_REASONS.undefinedValue],
  ["sunMeta/MGroup.testSet/particles00203m1/Positive", W3C_CORPUS_REASONS.undefinedValue],
  ["sunMeta/SType.testSet/st_name00401m/ST_name00401m1_p", W3C_CORPUS_REASONS.needsTriage],
  ["sunMeta/SType.testSet/st_targetns00101m/ST_targetNS00101m1_p", W3C_CORPUS_REASONS.needsTriage],
  ["sunMeta/SType.testSet/st_targetns00101m/ST_targetNS00101m2_p", W3C_CORPUS_REASONS.needsTriage],
  ["sunMeta/SType.testSet/st_targetns00201m/ST_targetNS00201m1_p", W3C_CORPUS_REASONS.needsTriage],
  ["sunMeta/suntest.testSet/xsd001/xsd001.v00", W3C_CORPUS_REASONS.needsTriage],
  ["sunMeta/suntest.testSet/xsd001/xsd001.v01", W3C_CORPUS_REASONS.needsTriage],
  ["sunMeta/suntest.testSet/xsd001/xsd001.v02", W3C_CORPUS_REASONS.needsTriage],
  ["sunMeta/suntest.testSet/xsd001/xsd001.v03", W3C_CORPUS_REASONS.needsTriage],
  ["boeingMeta/BoeingXSDTestSet.testSet/ipo6/ipo_1", W3C_CORPUS_REASONS.choiceDocumentOrder],
]);
