// Known failures for the full-corpus suite (#108 Phase 4), keyed by
// `<testSet-relative-path>/<testGroup>/<instanceTest>`. Entries run as
// `it.fails` — a fix that makes a case pass turns the suite red; remove the
// entry in the same PR. Generated from full corpus runs, then hand-maintained.
export const W3C_CORPUS_REASONS = {
  choiceDocumentOrder:
    "choice: interleaved repeated branches collapse into per-element arrays; document order is lost and the serialized XML no longer validates",
  libxmlRejectsSerialized: "libxml2 rejects serialized XML (needs triage)",
  libxmlStrictWildcardXsiType:
    "libxml2 gap: strict-wildcard item with xsi:type but no global element declaration is rejected — the XSD xsi:type fallback is unimplemented (the original instance fails libxml2 too)",
  libxmlGap:
    "libxml2 gap: the original instance/schema fails libxml2 itself (pre-errata XSD 1.0 gMonth lexical, maxOccurs beyond libxml2's integer range) — the zod-tier round-trip succeeds",
  needsTriage: "needs triage",
  requiredArrayEmpty: "cardinality: required element array parsed empty (needs triage)",
  patternOnNonString:
    "runtime: pattern checked against coerced value, not the original lexical (lexical preservation needed)",
  simpleContentShape: "parse: simpleContent _text shape mismatch (needs triage)",
} as const;

export const W3C_CORPUS_KNOWN_FAILURES = new Map<string, string>([
  ["msMeta/Additional_w3c.xml/addB116/addB116.v", W3C_CORPUS_REASONS.libxmlStrictWildcardXsiType],
  ["msMeta/Additional_w3c.xml/addB187/addB187.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/Additional_w3c.xml/isDefault079/isDefault079.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/Attribute_w3c.xml/attO009/attO009.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/Attribute_w3c.xml/attO011/attO011.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/DataTypes_w3c.xml/gMonth002_2061/gMonth002_2061.v", W3C_CORPUS_REASONS.libxmlGap],
  ["msMeta/DataTypes_w3c.xml/gMonth004_2063/gMonth004_2063.v", W3C_CORPUS_REASONS.libxmlGap],
  ["msMeta/Element_w3c.xml/QFE1700c2/QFE1700c2.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/Group_w3c.xml/groupF009v/groupF009v.v", W3C_CORPUS_REASONS.libxmlGap],
  ["msMeta/Group_w3c.xml/groupH009v/groupH009v.v", W3C_CORPUS_REASONS.libxmlGap],
  ["msMeta/Group_w3c.xml/groupJ009v/groupJ009v.v", W3C_CORPUS_REASONS.libxmlGap],
  ["msMeta/Group_w3c.xml/groupL009v/groupL009v.v", W3C_CORPUS_REASONS.libxmlGap],
  ["msMeta/Group_w3c.xml/groupN009v/groupN009v.v", W3C_CORPUS_REASONS.libxmlGap],
  ["msMeta/IdentityConstraint_w3c.xml/idF012/idF012.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/IdentityConstraint_w3c.xml/idF013/idF013.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/IdentityConstraint_w3c.xml/idF014/idF014.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/ModelGroups_w3c.xml/mgA015/mgA015.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],

  ["msMeta/ModelGroups_w3c.xml/mgO006/mgO006.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/ModelGroups_w3c.xml/mgQ003/mgQ003.v", W3C_CORPUS_REASONS.choiceDocumentOrder],
  [
    "msMeta/Particles_w3c.xml/particlesQ030/particlesQ030.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  [
    "msMeta/Particles_w3c.xml/particlesQ032/particlesQ032.v",
    W3C_CORPUS_REASONS.libxmlRejectsSerialized,
  ],
  ["msMeta/Particles_w3c.xml/particlesZ005/particlesZ005.v", W3C_CORPUS_REASONS.needsTriage],
  ["msMeta/Particles_w3c.xml/particlesZ012/particlesZ012.v", W3C_CORPUS_REASONS.needsTriage],
  [
    "msMeta/Regex_w3c.xml/ArabicPresentationForms-A/ArabicPresentationForms-A.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  [
    "msMeta/Regex_w3c.xml/Latin-1Supplement/Latin-1Supplement.v",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  ["msMeta/Regex_w3c.xml/LatinExtended-A/LatinExtended-A.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/LatinExtended-B/LatinExtended-B.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/RegexTest_42/RegexTest_42.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/RegexTest_73/RegexTest_73.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/p16/p16.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/p17/p17.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/p20/p20.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reDF1/reDF1.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reDF2/reDF2.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reF43/reF43.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reG11/reG11.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reG13/reG13.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reI29/reI29.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reI31/reI31.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reJ53/reJ53.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reJ55/reJ55.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reJ57/reJ57.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reJ59/reJ59.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reJ73/reJ73.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reK4/reK4.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/Regex_w3c.xml/reL2/reL2.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL3/reL3.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL4/reL4.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL81/reL81.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reL85/reL85.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reO2/reO2.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reP2/reP2.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reP4/reP4.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reQ18/reQ18.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reQ20/reQ20.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reR20/reR20.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reR22/reR22.v", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/Regex_w3c.xml/reZ006i/reZ006i.i", W3C_CORPUS_REASONS.patternOnNonString],
  ["msMeta/SimpleType_w3c.xml/stE065/stE065.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["msMeta/SimpleType_w3c.xml/stE066/stE066.v", W3C_CORPUS_REASONS.libxmlRejectsSerialized],
  ["sunMeta/CType.testSet/basetd00101m1/Positive", W3C_CORPUS_REASONS.simpleContentShape],
  ["sunMeta/CType.testSet/targetns00101m/targetNS00101m1_p", W3C_CORPUS_REASONS.needsTriage],
  ["sunMeta/ElemDecl.testSet/targetns00101m/targetNS00101m1_p", W3C_CORPUS_REASONS.needsTriage],
  [
    "sunMeta/ElemDecl.testSet/valueconstraint00501m1/Positive",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  [
    "sunMeta/ElemDecl.testSet/valueconstraint00501m2/Positive",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  [
    "sunMeta/ElemDecl.testSet/valueconstraint00501m4/Positive",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  [
    "sunMeta/ElemDecl.testSet/valueconstraint00501m5/Positive",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  [
    "sunMeta/ElemDecl.testSet/valueconstraint00601m7/Positive",
    W3C_CORPUS_REASONS.patternOnNonString,
  ],
  ["sunMeta/SType.testSet/st_name00401m/ST_name00401m1_p", W3C_CORPUS_REASONS.needsTriage],
  ["sunMeta/SType.testSet/st_targetns00101m/ST_targetNS00101m1_p", W3C_CORPUS_REASONS.needsTriage],
  ["sunMeta/SType.testSet/st_targetns00101m/ST_targetNS00101m2_p", W3C_CORPUS_REASONS.needsTriage],
  ["sunMeta/SType.testSet/st_targetns00201m/ST_targetNS00201m1_p", W3C_CORPUS_REASONS.needsTriage],
]);
