// Known failures for the W3C sun/ms selection (#108), keyed by
// `<testSetName>/<testGroup>/<instanceTest>`. Each entry pins a genuine bug
// or an unsupported feature with its reason. Entries run as `it.fails`, so a
// fix that makes a case pass turns the suite red — remove the entry in the
// same PR that lands the fix. Generated from a full vitest run, then
// hand-maintained.
export const W3C_KNOWN_FAILURES = new Map<string, string>([
  ['AGroupDef/ag_attrusens00101m1_p/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['AGroupDef/ag_attrwcard00101m1/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['AGroupDef/ag_name00101m1_p/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['AGroupDef/ag_targetns00101m1_p/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['AGroupDef/annotation00101m1/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['AGroupDef/annotation00101m4/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['AttrDecl/ad_annotation00101m1/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['AttrDecl/ad_annotation00101m2/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['AttrDecl/ad_scope00101m1/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['Attribute/attD007/attD007.v', 'codegen: length facets emitted on non-string schema (list/union-derived)'],
  ['Attribute/attO009/attO009.v', 'needs triage'],
  ['Attribute/attO010/attO010.v', 'needs triage'],
  ['Attribute/attO011/attO011.v', 'needs triage'],
  ['AttributeGroup/attgC007/attgC007.v', 'codegen: stack overflow on recursive type/group'],
  ['AttributeGroup/attgC035/attgC035.v', 'codegen: stack overflow on recursive type/group'],
  ['AttributeGroup/attgC036/attgC036.v', 'codegen: stack overflow on recursive type/group'],
  ['AttributeGroup/attgC037/attgC037.v', 'codegen: stack overflow on recursive type/group'],
  ['AttributeGroup/attgC038/attgC038.v', 'codegen: stack overflow on recursive type/group'],
  ['AttributeGroup/attgD036/attgD036.v', 'codegen: stack overflow on recursive type/group'],
  ['AttrUse/au_attrdecl00101m1_p/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['AttrUse/au_required00101m1/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ComplexType/ctA002/ctA002.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['ComplexType/ctA003/ctA003.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['ComplexType/ctE018/ctE018.v', 'parse: element value arrives as undefined (needs triage)'],
  ['ComplexType/ctE019/ctE019.v', 'parse: element value arrives as undefined (needs triage)'],
  ['ComplexType/ctH025/ctH025.v', 'choice validation rejects a valid branch combination (needs triage)'],
  ['ComplexType/ctH031/ctH031.v', 'choice validation rejects a valid branch combination (needs triage)'],
  ['ComplexType/ctH032/ctH032.v', 'choice validation rejects a valid branch combination (needs triage)'],
  ['ComplexType/ctH033/ctH033.v', 'choice validation rejects a valid branch combination (needs triage)'],
  ['ComplexType/ctH034/ctH034.v', 'choice validation rejects a valid branch combination (needs triage)'],
  ['ComplexType/ctH035/ctH035.v', 'choice validation rejects a valid branch combination (needs triage)'],
  ['ComplexType/ctI003/ctI003.v', 'runtime: xs:integer value beyond MAX_SAFE_INTEGER rejected'],
  ['ComplexType/ctL003/ctL003.v', 'parse: element value arrives as undefined (needs triage)'],
  ['ComplexType/ctL022/ctL022.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['ComplexType/ctZ007/ctZ007.v', 'cardinality: required element array parsed empty (needs triage)'],
  ['CType/annotation00101m1/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['CType/annotation00101m2/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['CType/basetd00101m1/Positive', 'parse: simpleContent _text shape mismatch (needs triage)'],
  ['CType/basetd00101m2/Positive', 'parse: simpleContent _text shape mismatch (needs triage)'],
  ['CType/targetns00101m/targetNS00101m1_p', 'needs triage'],
  ['DataTypes/anyURI_a002_1337/anyURI_a002_1337.v', 'harness: test-set file resolution (needs triage)'],
  ['DataTypes/base64Binary_length002_1310/base64Binary_length002_1310.v', 'codegen: length facet unit wrong for list/binary types (items/octets vs chars)'],
  ['DataTypes/base64Binary_minLength004_1315/base64Binary_minLength004_1315.v', 'needs triage'],
  ['DataTypes/boolean018_1874/boolean018_1874.v', 'needs triage'],
  ['DataTypes/byte_pattern001_1682/byte_pattern001_1682.v', 'codegen: pattern facet emitted on non-string schema'],
  ['DataTypes/date_maxExclusive003_1179/date_maxExclusive003_1179.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/date_maxInclusive001_1174/date_maxInclusive001_1174.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/date_maxInclusive003_1176/date_maxInclusive003_1176.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/date_minExclusive003_1187/date_minExclusive003_1187.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/date_minExclusive004_1188/date_minExclusive004_1188.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/date_minExclusive005_1189/date_minExclusive005_1189.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/date_minInclusive001_1180/date_minInclusive001_1180.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/date_minInclusive003_1182/date_minInclusive003_1182.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/date_minInclusive004_1183/date_minInclusive004_1183.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/date_minInclusive005_1184/date_minInclusive005_1184.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/dateTime_enumeration005a_1129/dateTime_enumeration005a_1129.v', 'runtime: dateTime -00:00 timezone lexical handling (needs triage)'],
  ['DataTypes/dateTime_enumeration005b_1130/dateTime_enumeration005b_1130.v', 'runtime: dateTime -00:00 timezone lexical handling (needs triage)'],
  ['DataTypes/dateTime_maxExclusive003_1136/dateTime_maxExclusive003_1136.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/dateTime_maxInclusive001_1131/dateTime_maxInclusive001_1131.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/dateTime_maxInclusive003_1133/dateTime_maxInclusive003_1133.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/dateTime_minExclusive003_1144/dateTime_minExclusive003_1144.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/dateTime_minExclusive004_1145/dateTime_minExclusive004_1145.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/dateTime_minExclusive005_1146/dateTime_minExclusive005_1146.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/dateTime_minInclusive001_1137/dateTime_minInclusive001_1137.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/dateTime_minInclusive003_1139/dateTime_minInclusive003_1139.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/dateTime_minInclusive004_1140/dateTime_minInclusive004_1140.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/dateTime_minInclusive005_1141/dateTime_minInclusive005_1141.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/decimal_pattern001_1036/decimal_pattern001_1036.v', 'codegen: pattern facet emitted on non-string schema'],
  ['DataTypes/decimal005_1879/decimal005_1879.v', 'round-trip: -0 sign lost in serialization'],
  ['DataTypes/decimal007_1881/decimal007_1881.v', 'round-trip: -0 sign lost in serialization'],
  ['DataTypes/decimal015_1889/decimal015_1889.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['DataTypes/decimal016_1890/decimal016_1890.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['DataTypes/double_pattern001_1082/double_pattern001_1082.v', 'codegen: pattern facet emitted on non-string schema'],
  ['DataTypes/double008_1946/double008_1946.v', 'round-trip: -0 sign lost in serialization'],
  ['DataTypes/double010_1948/double010_1948.v', 'round-trip: -0 sign lost in serialization'],
  ['DataTypes/double019_1957/double019_1957.v', 'runtime: INF/-INF/NaN double lexicals unsupported'],
  ['DataTypes/double020_1958/double020_1958.v', 'runtime: INF/-INF/NaN double lexicals unsupported'],
  ['DataTypes/double021_1959/double021_1959.v', 'runtime: INF/-INF/NaN double lexicals unsupported'],
  ['DataTypes/double030_1968/double030_1968.v', 'runtime: INF/-INF/NaN double lexicals unsupported'],
  ['DataTypes/duration_maxExclusive003_1113/duration_maxExclusive003_1113.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/duration_maxInclusive001_1108/duration_maxInclusive001_1108.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/duration_maxInclusive003_1110/duration_maxInclusive003_1110.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/duration_minExclusive003_1121/duration_minExclusive003_1121.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/duration_minExclusive004_1122/duration_minExclusive004_1122.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/duration_minExclusive005_1123/duration_minExclusive005_1123.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/duration_minInclusive001_1114/duration_minInclusive001_1114.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/duration_minInclusive003_1116/duration_minInclusive003_1116.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/duration_minInclusive004_1117/duration_minInclusive004_1117.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/duration_minInclusive005_1118/duration_minInclusive005_1118.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/duration_pattern001_1103/duration_pattern001_1103.v', 'codegen: XSD pattern facet regex translation too strict (needs triage)'],
  ['DataTypes/float_pattern001_1061/float_pattern001_1061.v', 'codegen: pattern facet emitted on non-string schema'],
  ['DataTypes/float008_1907/float008_1907.v', 'round-trip: -0 sign lost in serialization'],
  ['DataTypes/float010_1909/float010_1909.v', 'round-trip: -0 sign lost in serialization'],
  ['DataTypes/float019_1918/float019_1918.v', 'runtime: INF/-INF/NaN double lexicals unsupported'],
  ['DataTypes/float020_1919/float020_1919.v', 'runtime: INF/-INF/NaN double lexicals unsupported'],
  ['DataTypes/float021_1920/float021_1920.v', 'runtime: INF/-INF/NaN double lexicals unsupported'],
  ['DataTypes/float039_1938/float039_1938.v', 'runtime: INF/-INF/NaN double lexicals unsupported'],
  ['DataTypes/gDay_maxExclusive003_1263/gDay_maxExclusive003_1263.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gDay_maxInclusive001_1258/gDay_maxInclusive001_1258.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gDay_maxInclusive003_1260/gDay_maxInclusive003_1260.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gDay_minExclusive003_1271/gDay_minExclusive003_1271.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gDay_minExclusive004_1272/gDay_minExclusive004_1272.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gDay_minExclusive005_1273/gDay_minExclusive005_1273.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gDay_minInclusive001_1264/gDay_minInclusive001_1264.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gDay_minInclusive003_1266/gDay_minInclusive003_1266.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gDay_minInclusive004_1267/gDay_minInclusive004_1267.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gDay_minInclusive005_1268/gDay_minInclusive005_1268.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gMonth002_2061/gMonth002_2061.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['DataTypes/gMonth004_2063/gMonth004_2063.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['DataTypes/gMonthDay_maxExclusive003_1242/gMonthDay_maxExclusive003_1242.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gMonthDay_maxInclusive001_1237/gMonthDay_maxInclusive001_1237.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gMonthDay_maxInclusive003_1239/gMonthDay_maxInclusive003_1239.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gMonthDay_minExclusive003_1250/gMonthDay_minExclusive003_1250.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gMonthDay_minExclusive004_1251/gMonthDay_minExclusive004_1251.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gMonthDay_minExclusive005_1252/gMonthDay_minExclusive005_1252.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gMonthDay_minInclusive001_1243/gMonthDay_minInclusive001_1243.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gMonthDay_minInclusive003_1245/gMonthDay_minInclusive003_1245.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gMonthDay_minInclusive004_1246/gMonthDay_minInclusive004_1246.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gMonthDay_minInclusive005_1247/gMonthDay_minInclusive005_1247.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gYear_maxExclusive003_1221/gYear_maxExclusive003_1221.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gYear_minExclusive003_1229/gYear_minExclusive003_1229.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gYear_minExclusive004_1230/gYear_minExclusive004_1230.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gYear_minExclusive005_1231/gYear_minExclusive005_1231.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gYear_minInclusive001_1222/gYear_minInclusive001_1222.v', 'needs triage'],
  ['DataTypes/gYear_minInclusive003_1224/gYear_minInclusive003_1224.v', 'needs triage'],
  ['DataTypes/gYear_minInclusive004_1225/gYear_minInclusive004_1225.v', 'needs triage'],
  ['DataTypes/gYear_minInclusive005_1226/gYear_minInclusive005_1226.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gYearMonth_maxExclusive003_1200/gYearMonth_maxExclusive003_1200.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gYearMonth_maxInclusive001_1195/gYearMonth_maxInclusive001_1195.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gYearMonth_maxInclusive003_1197/gYearMonth_maxInclusive003_1197.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gYearMonth_minExclusive003_1208/gYearMonth_minExclusive003_1208.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gYearMonth_minExclusive004_1209/gYearMonth_minExclusive004_1209.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gYearMonth_minExclusive005_1210/gYearMonth_minExclusive005_1210.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gYearMonth_minInclusive001_1201/gYearMonth_minInclusive001_1201.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gYearMonth_minInclusive003_1203/gYearMonth_minInclusive003_1203.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gYearMonth_minInclusive004_1204/gYearMonth_minInclusive004_1204.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/gYearMonth_minInclusive005_1205/gYearMonth_minInclusive005_1205.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/hexBinary_length002_1296/hexBinary_length002_1296.v', 'codegen: length facet unit wrong for list/binary types (items/octets vs chars)'],
  ['DataTypes/hexBinary_maxLength001_1302/hexBinary_maxLength001_1302.v', 'needs triage'],
  ['DataTypes/hexBinary_minLength004_1301/hexBinary_minLength004_1301.v', 'needs triage'],
  ['DataTypes/ID_test70681_2241/ID_test70681_2241.v', 'parse: element value arrives as undefined (needs triage)'],
  ['DataTypes/IDREFS_length002_1433/IDREFS_length002_1433.v', 'codegen: length facet unit wrong for list/binary types (items/octets vs chars)'],
  ['DataTypes/IDREFS_maxLength002_1440/IDREFS_maxLength002_1440.v', 'needs triage'],
  ['DataTypes/IDREFS_maxLength003_1441/IDREFS_maxLength003_1441.v', 'needs triage'],
  ['DataTypes/IDREFS_minLength004_1438/IDREFS_minLength004_1438.v', 'needs triage'],
  ['DataTypes/int_pattern001_1633/int_pattern001_1633.v', 'codegen: pattern facet emitted on non-string schema'],
  ['DataTypes/integer_pattern001_1537/integer_pattern001_1537.v', 'codegen: pattern facet emitted on non-string schema'],
  ['DataTypes/integer005_2145/integer005_2145.v', 'round-trip: -0 sign lost in serialization'],
  ['DataTypes/integer011_2151/integer011_2151.v', 'runtime: xs:integer value beyond MAX_SAFE_INTEGER rejected'],
  ['DataTypes/long_pattern001_1609/long_pattern001_1609.v', 'codegen: pattern facet emitted on non-string schema'],
  ['DataTypes/long005_2171/long005_2171.v', 'runtime: xs:integer value beyond MAX_SAFE_INTEGER rejected'],
  ['DataTypes/long007_2173/long007_2173.v', 'runtime: xs:integer value beyond MAX_SAFE_INTEGER rejected'],
  ['DataTypes/long009_2175/long009_2175.v', 'runtime: xs:integer value beyond MAX_SAFE_INTEGER rejected'],
  ['DataTypes/negativeInteger_pattern001_1585/negativeInteger_pattern001_1585.v', 'codegen: pattern facet emitted on non-string schema'],
  ['DataTypes/negativeInteger005_2166/negativeInteger005_2166.v', 'runtime: xs:integer value beyond MAX_SAFE_INTEGER rejected'],
  ['DataTypes/NMTOKENS_length002_1462/NMTOKENS_length002_1462.v', 'codegen: length facet unit wrong for list/binary types (items/octets vs chars)'],
  ['DataTypes/NMTOKENS_maxLength002_1469/NMTOKENS_maxLength002_1469.v', 'needs triage'],
  ['DataTypes/nonNegativeInteger_pattern001_1706/nonNegativeInteger_pattern001_1706.v', 'codegen: pattern facet emitted on non-string schema'],
  ['DataTypes/nonNegativeInteger005_2206/nonNegativeInteger005_2206.v', 'runtime: xs:integer value beyond MAX_SAFE_INTEGER rejected'],
  ['DataTypes/nonPositiveInteger_pattern001_1561/nonPositiveInteger_pattern001_1561.v', 'codegen: pattern facet emitted on non-string schema'],
  ['DataTypes/nonPositiveInteger005_2161/nonPositiveInteger005_2161.v', 'runtime: xs:integer value beyond MAX_SAFE_INTEGER rejected'],
  ['DataTypes/NOTATION_length001_1372/NOTATION_length001_1372.i', 'codegen: length facets emitted on xs:NOTATION schema'],
  ['DataTypes/NOTATION_length002_1373/NOTATION_length002_1373.v', 'codegen: length facets emitted on xs:NOTATION schema'],
  ['DataTypes/NOTATION_length003_1374/NOTATION_length003_1374.i', 'codegen: length facets emitted on xs:NOTATION schema'],
  ['DataTypes/NOTATION_maxLength001_1379/NOTATION_maxLength001_1379.i', 'codegen: length facets emitted on xs:NOTATION schema'],
  ['DataTypes/NOTATION_maxLength002_1380/NOTATION_maxLength002_1380.v', 'codegen: length facets emitted on xs:NOTATION schema'],
  ['DataTypes/NOTATION_maxLength003_1381/NOTATION_maxLength003_1381.v', 'codegen: length facets emitted on xs:NOTATION schema'],
  ['DataTypes/NOTATION_minLength001_1375/NOTATION_minLength001_1375.v', 'codegen: length facets emitted on xs:NOTATION schema'],
  ['DataTypes/NOTATION_minLength002_1376/NOTATION_minLength002_1376.v', 'codegen: length facets emitted on xs:NOTATION schema'],
  ['DataTypes/NOTATION_minLength003_1377/NOTATION_minLength003_1377.i', 'codegen: length facets emitted on xs:NOTATION schema'],
  ['DataTypes/NOTATION_minLength004_1378/NOTATION_minLength004_1378.v', 'codegen: length facets emitted on xs:NOTATION schema'],
  ['DataTypes/NOTATION_pattern001_1382/NOTATION_pattern001_1382.v', 'codegen: pattern facet emitted on non-string schema'],
  ['DataTypes/positiveInteger_pattern001_1826/positiveInteger_pattern001_1826.v', 'codegen: pattern facet emitted on non-string schema'],
  ['DataTypes/positiveInteger005_2239/positiveInteger005_2239.v', 'runtime: xs:integer value beyond MAX_SAFE_INTEGER rejected'],
  ['DataTypes/QName_enumeration002_1369/QName_enumeration002_1369.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['DataTypes/QName_enumeration004_1371/QName_enumeration004_1371.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['DataTypes/QName_length001_1357/QName_length001_1357.i', 'codegen: length facet unit wrong for list/binary types (items/octets vs chars)'],
  ['DataTypes/QName_length003_1359/QName_length003_1359.i', 'codegen: length facet unit wrong for list/binary types (items/octets vs chars)'],
  ['DataTypes/QName_maxLength001_1364/QName_maxLength001_1364.i', 'needs triage'],
  ['DataTypes/QName_minLength003_1362/QName_minLength003_1362.i', 'needs triage'],
  ['DataTypes/QName006_2089/QName006_2089.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['DataTypes/short_pattern001_1658/short_pattern001_1658.v', 'codegen: pattern facet emitted on non-string schema'],
  ['DataTypes/time_maxExclusive003_1157/time_maxExclusive003_1157.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/time_maxInclusive001_1152/time_maxInclusive001_1152.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/time_maxInclusive003_1154/time_maxInclusive003_1154.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/time_minExclusive003_1166/time_minExclusive003_1166.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/time_minExclusive004_1167/time_minExclusive004_1167.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/time_minExclusive005_1168/time_minExclusive005_1168.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/time_minInclusive001_1158/time_minInclusive001_1158.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/time_minInclusive003_1160/time_minInclusive003_1160.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/time_minInclusive004_1161/time_minInclusive004_1161.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/time_minInclusive005_1162/time_minInclusive005_1162.v', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['DataTypes/unsignedByte_pattern001_1802/unsignedByte_pattern001_1802.v', 'codegen: pattern facet emitted on non-string schema'],
  ['DataTypes/unsignedInt_pattern001_1754/unsignedInt_pattern001_1754.v', 'codegen: pattern facet emitted on non-string schema'],
  ['DataTypes/unsignedLong_pattern001_1730/unsignedLong_pattern001_1730.v', 'codegen: pattern facet emitted on non-string schema'],
  ['DataTypes/unsignedLong005_2211/unsignedLong005_2211.v', 'runtime: xs:integer value beyond MAX_SAFE_INTEGER rejected'],
  ['DataTypes/unsignedLong007_2213/unsignedLong007_2213.v', 'runtime: xs:integer value beyond MAX_SAFE_INTEGER rejected'],
  ['DataTypes/unsignedShort_pattern001_1778/unsignedShort_pattern001_1778.v', 'codegen: pattern facet emitted on non-string schema'],
  ['ElemDecl/abstract00101m/abstract00101m1_p', 'cardinality: required element array parsed empty (needs triage)'],
  ['ElemDecl/abstract00201m2/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/abstract00201m3/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/annotation00101m1/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/annotation00101m3/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/disallowedsubst00301m1/Positive', 'unsupported: substitution groups'],
  ['ElemDecl/disallowedsubst00401m1/Positive', 'unsupported: substitution groups'],
  ['ElemDecl/disallowedsubst00501m1/Positive', 'unsupported: substitution groups'],
  ['ElemDecl/disallowedsubst00502m1/Positive', 'unsupported: substitution groups'],
  ['ElemDecl/disallowedsubst00502m2/Positive', 'unsupported: substitution groups'],
  ['ElemDecl/disallowedsubst00503m1/Positive', 'unsupported: substitution groups'],
  ['ElemDecl/disallowedsubst00503m2/Positive', 'unsupported: substitution groups'],
  ['ElemDecl/name00201m2/Positive', 'codegen: pattern facet emitted on non-string schema'],
  ['ElemDecl/name00301m1/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/name00401m1/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/name00401m2/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/name00501m1/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/name00501m11/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/name00501m13/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/name00501m14/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/name00501m15/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/name00501m3/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/name00501m5/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/name00501m7/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/name00501m9/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/name00502m1/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/name00503m1/Positive', 'codegen: pattern facet emitted on non-string schema'],
  ['ElemDecl/name00504m1/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/name00504m3/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/name00601m/name00601m1_p', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/nillable00201m/nillable00201m3_p', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/nillable00401m1/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/nillable00401m2/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/substgrpaffil00101m/substGrpAffil00101m1_p', 'cardinality: required element array parsed empty (needs triage)'],
  ['ElemDecl/targetns00101m/targetNS00101m1_p', 'needs triage'],
  ['ElemDecl/targetns00401m/targetNS00401m1_p', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/targetns00402m/targetNS00402m1_p', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/typedef00201m/typeDef00201m1_p', 'codegen: pattern facet emitted on non-string schema'],
  ['ElemDecl/typedef00205m/typeDef00205m1_p', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/typedef00403m/typeDef00403m1_p', 'codegen: pattern facet emitted on non-string schema'],
  ['ElemDecl/typedef00502m1/Positive', 'codegen: pattern facet emitted on non-string schema'],
  ['ElemDecl/typedef00701m/typeDef00701m1_p', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/typedef00802m1/Positive', 'codegen: pattern facet emitted on non-string schema'],
  ['ElemDecl/typedef00901m1/Positive', 'codegen: pattern facet emitted on non-string schema'],
  ['ElemDecl/typedef01101m1/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/typedef01301m1/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/valueconstraint00101m1/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/valueconstraint00301m1/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/valueconstraint00301m2/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/valueconstraint00401m1/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/valueconstraint00401m3/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/valueconstraint00401m4/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/valueconstraint00401m5/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/valueconstraint00401m7/Positive', 'codegen: pattern facet emitted on non-string schema'],
  ['ElemDecl/valueconstraint00401m9/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/valueconstraint00402m1/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/valueconstraint00402m3/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/valueconstraint00402m4/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/valueconstraint00402m5/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/valueconstraint00402m7/Positive', 'codegen: pattern facet emitted on non-string schema'],
  ['ElemDecl/valueconstraint00402m9/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/valueconstraint00501m1/Positive', 'codegen: pattern facet emitted on non-string schema'],
  ['ElemDecl/valueconstraint00501m2/Positive', 'codegen: pattern facet emitted on non-string schema'],
  ['ElemDecl/valueconstraint00501m4/Positive', 'codegen: pattern facet emitted on non-string schema'],
  ['ElemDecl/valueconstraint00501m5/Positive', 'codegen: pattern facet emitted on non-string schema'],
  ['ElemDecl/valueconstraint00601m1/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/valueconstraint00601m3/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/valueconstraint00601m5/Positive', 'codegen: pattern facet emitted on non-string schema'],
  ['ElemDecl/valueconstraint00601m7/Positive', 'codegen: pattern facet emitted on non-string schema'],
  ['ElemDecl/valueconstraint01001m1/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/valueconstraint01001m4/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/valueconstraint01001m7/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ElemDecl/valueconstraint01001m8/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['Element/elemO004/elemO004.v', 'runtime: xs:integer value beyond MAX_SAFE_INTEGER rejected'],
  ['Element/elemO005/elemO005.v', 'runtime: xs:integer value beyond MAX_SAFE_INTEGER rejected'],
  ['Element/elemS002/elemS002.v', 'needs triage'],
  ['Element/elemS003/elemS003.v', 'parse: element value arrives as undefined (needs triage)'],
  ['Element/elemS007/elemS007.v', 'parse: element value arrives as undefined (needs triage)'],
  ['Element/elemS008/elemS008.v', 'needs triage'],
  ['Element/elemU005/elemU005.v', 'codegen: XSD pattern facet regex translation too strict (needs triage)'],
  ['Element/elemU006/elemU006.v', 'codegen: XSD pattern facet regex translation too strict (needs triage)'],
  ['Element/elemU007/elemU007.v', 'codegen: XSD pattern facet regex translation too strict (needs triage)'],
  ['Element/elemZ014/elemZ014.v', 'parse: element value arrives as undefined (needs triage)'],
  ['Element/elemZ019/elemZ019.v', 'parse: element value arrives as undefined (needs triage)'],
  ['Element/elemZ021d/elemZ021d.v', 'parse: element value arrives as undefined (needs triage)'],
  ['Element/QFE1700a1/QFE1700a1.v', 'unsupported: xs:any wildcard content'],
  ['Element/QFE1700a2/QFE1700a2.v', 'unsupported: xs:any wildcard content'],
  ['Element/QFE1700a3/QFE1700a3.v', 'unsupported: xs:any wildcard content'],
  ['Element/QFE1700b1/QFE1700b1.v', 'unsupported: xs:any wildcard content'],
  ['Element/QFE1700b2/QFE1700b2.v', 'unsupported: xs:any wildcard content'],
  ['Element/QFE1700c2/QFE1700c2.v', 'needs triage'],
  ['Group/groupF009v/groupF009v.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['Group/groupG004v/groupG004v.v', 'cardinality: required element array parsed empty (needs triage)'],
  ['Group/groupH009v/groupH009v.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['Group/groupH011v/groupH011v.v', 'choice validation rejects a valid branch combination (needs triage)'],
  ['Group/groupH014v/groupH014v.v', 'choice validation rejects a valid branch combination (needs triage)'],
  ['Group/groupH017v/groupH017v.v', 'needs triage'],
  ['Group/groupH018v/groupH018v.v', 'choice validation rejects a valid branch combination (needs triage)'],
  ['Group/groupJ009v/groupJ009v.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['Group/groupL009v/groupL009v.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['Group/groupN009v/groupN009v.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['MGroup/annotation00101m1/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['MGroup/annotation00101m10/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['MGroup/annotation00101m13/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['MGroup/annotation00101m16/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['MGroup/annotation00101m4/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['MGroup/annotation00101m7/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['MGroup/compositor00202m1/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['MGroup/particles00203m1/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['MGroup/particles00301m1/Positive', 'runtime: xs:integer value beyond MAX_SAFE_INTEGER rejected'],
  ['MGroup/particles00302m1/Positive', 'runtime: xs:integer value beyond MAX_SAFE_INTEGER rejected'],
  ['MGroupDef/annotation00101m1/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['MGroupDef/annotation00101m4/Positive', 'parse: element value arrives as undefined (needs triage)'],
  ['ModelGroups/mgA015/mgA015.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['ModelGroups/mgA017/mgA017.v', 'parse: element value arrives as undefined (needs triage)'],
  ['ModelGroups/mgE016/mgE016.v', 'parse: element value arrives as undefined (needs triage)'],
  ['ModelGroups/mgF008/mgF008.v', 'unsupported: xs:any wildcard content'],
  ['ModelGroups/mgF009/mgF009.v', 'unsupported: xs:any wildcard content'],
  ['ModelGroups/mgF010/mgF010.v', 'unsupported: xs:any wildcard content'],
  ['ModelGroups/mgF011/mgF011.v', 'unsupported: xs:any wildcard content'],
  ['ModelGroups/mgF012/mgF012.v', 'unsupported: xs:any wildcard content'],
  ['ModelGroups/mgF013/mgF013.v', 'unsupported: xs:any wildcard content'],
  ['ModelGroups/mgF014/mgF014.v', 'unsupported: xs:any wildcard content'],
  ['ModelGroups/mgF018/mgF018.v', 'unsupported: xs:any wildcard content'],
  ['ModelGroups/mgF019/mgF019.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['ModelGroups/mgI008/mgI008.v', 'unsupported: xs:any wildcard content'],
  ['ModelGroups/mgI009/mgI009.v', 'choice validation rejects a valid branch combination (needs triage)'],
  ['ModelGroups/mgI010/mgI010.v', 'needs triage'],
  ['ModelGroups/mgI011/mgI011.v', 'needs triage'],
  ['ModelGroups/mgI012/mgI012.v', 'choice validation rejects a valid branch combination (needs triage)'],
  ['ModelGroups/mgI013/mgI013.v', 'needs triage'],
  ['ModelGroups/mgI014/mgI014.v', 'choice validation rejects a valid branch combination (needs triage)'],
  ['ModelGroups/mgI015/mgI015.v', 'choice validation rejects a valid branch combination (needs triage)'],
  ['ModelGroups/mgI016/mgI016.v', 'parse: element value arrives as undefined (needs triage)'],
  ['ModelGroups/mgI017/mgI017.v', 'parse: element value arrives as undefined (needs triage)'],
  ['ModelGroups/mgI018/mgI018.v', 'choice validation rejects a valid branch combination (needs triage)'],
  ['ModelGroups/mgM013/mgM013.v', 'parse: element value arrives as undefined (needs triage)'],
  ['ModelGroups/mgO006/mgO006.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['ModelGroups/mgQ002/mgQ002.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['ModelGroups/mgQ003/mgQ003.v', 'choice validation rejects a valid branch combination (needs triage)'],
  ['Particles/particlesA006/particlesA006.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['Particles/particlesA007/particlesA007.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['Particles/particlesA014/particlesA014.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesA015/particlesA015.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesB013/particlesB013.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesB014/particlesB014.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesC001/particlesC001.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesC002/particlesC002.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesC003/particlesC003.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesC004/particlesC004.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesC005/particlesC005.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesC006/particlesC006.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesC008/particlesC008.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesC011/particlesC011.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesC015/particlesC015.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesC016/particlesC016.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesDc001/particlesDc001.v', 'parse: element value arrives as undefined (needs triage)'],
  ['Particles/particlesDc002/particlesDc002.v', 'parse: element value arrives as undefined (needs triage)'],
  ['Particles/particlesDc003/particlesDc003.v', 'parse: element value arrives as undefined (needs triage)'],
  ['Particles/particlesDc007/particlesDc007.v', 'parse: element value arrives as undefined (needs triage)'],
  ['Particles/particlesEb027/particlesEb027.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['Particles/particlesEb036/particlesEb036.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['Particles/particlesEb038/particlesEb038.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['Particles/particlesFa005/particlesFa005.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesFb001/particlesFb001.v', 'choice validation rejects a valid branch combination (needs triage)'],
  ['Particles/particlesHa015/particlesHa015.v', 'parse: element value arrives as undefined (needs triage)'],
  ['Particles/particlesIb005/particlesIb005.v', 'parse: element value arrives as undefined (needs triage)'],
  ['Particles/particlesIe004/particlesIe004.v', 'choice validation rejects a valid branch combination (needs triage)'],
  ['Particles/particlesJs001/particlesJs001.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['Particles/particlesOa001/particlesOa001.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesOa003/particlesOa003.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesOa006/particlesOa006.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesOa011/particlesOa011.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesOa012/particlesOa012.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesOa013/particlesOa013.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesOa014/particlesOa014.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesOb003/particlesOb003.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesOb005/particlesOb005.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesOb006/particlesOb006.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesOb007/particlesOb007.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesOb012/particlesOb012.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesOb015/particlesOb015.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesOb022/particlesOb022.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['Particles/particlesOb032/particlesOb032.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesOb047/particlesOb047.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesOb048/particlesOb048.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesOb052/particlesOb052.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['Particles/particlesOb053/particlesOb053.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesOb054/particlesOb054.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesOb055/particlesOb055.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesOb056/particlesOb056.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesOb057/particlesOb057.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesOb059/particlesOb059.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesOb060/particlesOb060.v', 'unsupported: xs:any wildcard content'],
  ['Particles/particlesQ013/particlesQ013.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['Particles/particlesQ017/particlesQ017.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['Particles/particlesQ024/particlesQ024.v', 'needs triage'],
  ['Particles/particlesQ030/particlesQ030.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['Particles/particlesQ032/particlesQ032.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['Particles/particlesR016/particlesR016.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['Particles/particlesR022/particlesR022.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['Particles/particlesT003/particlesT003.v', 'choice validation rejects a valid branch combination (needs triage)'],
  ['Particles/particlesV003/particlesV003.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['Particles/particlesZ003/particlesZ003.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['Particles/particlesZ005/particlesZ005.v', 'needs triage'],
  ['Particles/particlesZ012/particlesZ012.v', 'needs triage'],
  ['Particles/particlesZ034_a1/particlesZ034_a1.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['SimpleType/stE050/stE050.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['SimpleType/stE055/stE055.v', 'needs triage'],
  ['SimpleType/stE065/stE065.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['SimpleType/stE066/stE066.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['SimpleType/stE079/stE079.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['SimpleType/stE091/stE091.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['SimpleType/stE092/stE092.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['SimpleType/stE093/stE093.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['SimpleType/stE094/stE094.v', 'libxml2 rejects serialized XML (needs triage)'],
  ['SimpleType/stG001/stG001.v', 'runtime: xs:integer value beyond MAX_SAFE_INTEGER rejected'],
  ['SimpleType/stG002/stG002.v', 'codegen: length facets emitted on non-string schema (list/union-derived)'],
  ['SimpleType/stG006/stG006.v', 'codegen: length facets emitted on non-string schema (list/union-derived)'],
  ['SimpleType/stG008/stG008.v', 'codegen: length facets emitted on non-string schema (list/union-derived)'],
  ['SimpleType/stG010/stG010.v', 'needs triage'],
  ['SimpleType/stG012/stG012.v', 'codegen: pattern facet emitted on non-string schema'],
  ['SimpleType/stH003/stH003.v', 'codegen: pattern facet emitted on non-string schema'],
  ['SimpleType/stH005/stH005.v', 'codegen: pattern facet emitted on non-string schema'],
  ['SimpleType/stH007/stH007.v', 'needs triage'],
  ['SimpleType/stZ008/stZ008.v', 'parse: element value arrives as undefined (needs triage)'],
  ['SimpleType/stZ040/stZ040.v', 'needs triage'],
  ['SimpleType/stZ046/stZ046.v', 'cardinality: required element array parsed empty (needs triage)'],
  ['SimpleType/stZ054/stZ054.v', 'parse: element value arrives as undefined (needs triage)'],
  ['SimpleType/stZ072/stZ072.v', 'needs triage'],
  ['SType/st_facets00118m/ST_facets00118m1_p', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['SType/st_facets00119m/ST_facets00119m1_p', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['SType/st_facets00121m/ST_facets00121m1_p', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['SType/st_facets00122m/ST_facets00122m1_p', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['SType/st_facets00123m/ST_facets00123m1_p', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['SType/st_facets00124m1/Positive', 'codegen: order facets (min/max In/Exclusive) emitted on string-typed schema'],
  ['SType/st_name00401m/ST_name00401m1_p', 'needs triage'],
  ['SType/st_targetns00101m/ST_targetNS00101m1_p', 'needs triage'],
  ['SType/st_targetns00101m/ST_targetNS00101m2_p', 'needs triage'],
  ['SType/st_targetns00201m/ST_targetNS00201m1_p', 'needs triage'],
  ['suntest/idc006.nogen/idc006.nogen.v00', 'unsupported: xs:any wildcard content'],
  ['suntest/identitytestsuitetest003/test.2.v', 'round-trip: -0 sign lost in serialization'],
  ['suntest/xsd001/xsd001.v00', 'needs triage'],
  ['suntest/xsd001/xsd001.v01', 'needs triage'],
  ['suntest/xsd001/xsd001.v02', 'needs triage'],
  ['suntest/xsd001/xsd001.v03', 'needs triage'],
  ['suntest/xsd002/xsd002.v00', 'parse: element value arrives as undefined (needs triage)'],
  ['suntest/xsd003b/xsd003b.v00', 'codegen: stack overflow on recursive type/group'],
  ['suntest/xsd003b/xsd003b.v01', 'codegen: stack overflow on recursive type/group'],
  ['suntest/xsd008/xsd008.v00', 'cardinality: required element array parsed empty (needs triage)'],
]);
