// Known failures for the W3C sun/ms selection (#108), keyed by
// `<testSetName>/<testGroup>/<instanceTest>`. Each entry pins a genuine bug
// or an unsupported feature with its reason. Entries run as `it.fails`, so a
// fix that makes a case pass turns the suite red — remove the entry in the
// same PR that lands the fix. Generated from a full vitest run, then
// hand-maintained.
export const REASONS = {
  undefinedValue: 'parse: element value arrives as undefined (needs triage)',
  facetPrecision: 'runtime: order-facet boundary precision lost via Number rounding',
  anyTypeContent: 'unsupported: xs:anyType content (element without a type maps to xs:string)',
  wildcard: 'unsupported: xs:any wildcard content',
  strictWildcardHarness: 'strict wildcard: extras re-serialized faithfully, but single-schema libxml2 validation cannot see cross-file declarations (harness limitation)',
  libxmlRejectsSerialized: 'libxml2 rejects serialized XML (needs triage)',
  needsTriage: 'needs triage',
  patternOnNonString: 'runtime: pattern checked against coerced value, not the original lexical (lexical preservation needed)',
  choiceValidation: 'nested choice groups: inner choice is enforced even when its outer branch is not selected (needs occurrence-aware validation)',
  integerBeyondSafeInt: 'runtime: xs:integer value beyond MAX_SAFE_INTEGER rejected',
  requiredArrayEmpty: 'cardinality: required element array parsed empty (needs triage)',
  substitutionGroups: 'unsupported: substitution groups',
  unionCoercion: 'runtime: union member coercion rejects a valid value (needs triage)',
  patternTranslation: 'codegen: XSD pattern facet regex translation too strict (needs triage)',
  simpleContentShape: 'parse: simpleContent _text shape mismatch (needs triage)',
  fileResolution: 'harness: test-set file resolution (needs triage)',
  dateTimeNegativeZeroTz: 'runtime: dateTime -00:00 timezone lexical handling (needs triage)',
} as const;

export const W3C_KNOWN_FAILURES = new Map<string, string>([
  ['Additional/addA005/addA005.v', REASONS.choiceValidation],
  ['Additional/addB012/addB012.v', REASONS.libxmlRejectsSerialized],
  ['Additional/addB058/addB058.v', REASONS.patternTranslation],
  ['Additional/addB067/addB067.v', REASONS.libxmlRejectsSerialized],
  ['Additional/addB068/addB068.i', REASONS.libxmlRejectsSerialized],
  ['Additional/addB090/addB090.v', REASONS.wildcard],
  ['Additional/addB116/addB116.v', REASONS.strictWildcardHarness],
  ['Additional/addB129/addB129.v', REASONS.integerBeyondSafeInt],
  ['Additional/addB135/addB135.v', REASONS.wildcard],
  ['Additional/addB145/addB145.v', REASONS.needsTriage],
  ['Additional/addB187/addB187.v', REASONS.needsTriage],
  ['Additional/addC001/addC001.v', REASONS.undefinedValue],
  ['Additional/isDefault072/isDefault072.v', REASONS.undefinedValue],
  ['Additional/isDefault078/isDefault078.v', REASONS.libxmlRejectsSerialized],
  ['Additional/isDefault079/isDefault079.v', REASONS.needsTriage],
  ['Additional/memberType004/memberType004.v', REASONS.libxmlRejectsSerialized],
  ['Additional/memberType008/memberType008.v', REASONS.libxmlRejectsSerialized],
  ['Attribute/attD007/attD007.v', REASONS.unionCoercion],
  ['Attribute/attO009/attO009.v', REASONS.needsTriage],
  ['Attribute/attO010/attO010.v', REASONS.needsTriage],
  ['Attribute/attO011/attO011.v', REASONS.needsTriage],
  ['AttributeGroup/attgD019/attgD019.v', REASONS.strictWildcardHarness],
  ['AttributeGroup/attgD020/attgD020.v', REASONS.strictWildcardHarness],
  ['AttributeGroup/attgD021/attgD021.v', REASONS.strictWildcardHarness],
  ['AttributeGroup/attgD022/attgD022.v', REASONS.strictWildcardHarness],
  ['AttributeGroup/attgD025/attgD025.v', REASONS.strictWildcardHarness],
  ['AttributeGroup/attgD034/attgD034.v', REASONS.strictWildcardHarness],
  ['ComplexType/ctA002/ctA002.v', REASONS.libxmlRejectsSerialized],
  ['ComplexType/ctA003/ctA003.v', REASONS.libxmlRejectsSerialized],
  ['ComplexType/ctI003/ctI003.v', REASONS.integerBeyondSafeInt],
  ['ComplexType/ctL021/ctL021.v', REASONS.strictWildcardHarness],
  ['ComplexType/ctL022/ctL022.v', REASONS.libxmlRejectsSerialized],
  ['ComplexType/ctZ007/ctZ007.v', REASONS.requiredArrayEmpty],
  ['CType/basetd00101m1/Positive', REASONS.simpleContentShape],
  ['CType/basetd00101m2/Positive', REASONS.simpleContentShape],
  ['CType/targetns00101m/targetNS00101m1_p', REASONS.needsTriage],
  ['DataTypes/anyURI_a002_1337/anyURI_a002_1337.v', REASONS.fileResolution],
  ['DataTypes/boolean018_1874/boolean018_1874.v', REASONS.needsTriage],
  ['DataTypes/byte_pattern001_1682/byte_pattern001_1682.v', REASONS.patternOnNonString],
  ['DataTypes/dateTime_enumeration005a_1129/dateTime_enumeration005a_1129.v', REASONS.dateTimeNegativeZeroTz],
  ['DataTypes/dateTime_enumeration005b_1130/dateTime_enumeration005b_1130.v', REASONS.dateTimeNegativeZeroTz],
  ['DataTypes/decimal015_1889/decimal015_1889.v', REASONS.libxmlRejectsSerialized],
  ['DataTypes/decimal016_1890/decimal016_1890.v', REASONS.libxmlRejectsSerialized],
  ['DataTypes/duration_pattern001_1103/duration_pattern001_1103.v', REASONS.patternTranslation],
  ['DataTypes/gMonth002_2061/gMonth002_2061.v', REASONS.libxmlRejectsSerialized],
  ['DataTypes/gMonth004_2063/gMonth004_2063.v', REASONS.libxmlRejectsSerialized],
  ['DataTypes/int_pattern001_1633/int_pattern001_1633.v', REASONS.patternOnNonString],
  ['DataTypes/integer_pattern001_1537/integer_pattern001_1537.v', REASONS.patternOnNonString],
  ['DataTypes/integer011_2151/integer011_2151.v', REASONS.integerBeyondSafeInt],
  ['DataTypes/long_pattern001_1609/long_pattern001_1609.v', REASONS.patternOnNonString],
  ['DataTypes/long005_2171/long005_2171.v', REASONS.integerBeyondSafeInt],
  ['DataTypes/long007_2173/long007_2173.v', REASONS.integerBeyondSafeInt],
  ['DataTypes/long009_2175/long009_2175.v', REASONS.integerBeyondSafeInt],
  ['DataTypes/negativeInteger_pattern001_1585/negativeInteger_pattern001_1585.v', REASONS.patternOnNonString],
  ['DataTypes/negativeInteger005_2166/negativeInteger005_2166.v', REASONS.integerBeyondSafeInt],
  ['DataTypes/nonNegativeInteger_pattern001_1706/nonNegativeInteger_pattern001_1706.v', REASONS.patternOnNonString],
  ['DataTypes/nonNegativeInteger005_2206/nonNegativeInteger005_2206.v', REASONS.integerBeyondSafeInt],
  ['DataTypes/nonPositiveInteger_pattern001_1561/nonPositiveInteger_pattern001_1561.v', REASONS.patternOnNonString],
  ['DataTypes/nonPositiveInteger005_2161/nonPositiveInteger005_2161.v', REASONS.integerBeyondSafeInt],
  ['DataTypes/positiveInteger_pattern001_1826/positiveInteger_pattern001_1826.v', REASONS.patternOnNonString],
  ['DataTypes/positiveInteger005_2239/positiveInteger005_2239.v', REASONS.integerBeyondSafeInt],
  ['DataTypes/QName_enumeration002_1369/QName_enumeration002_1369.v', REASONS.libxmlRejectsSerialized],
  ['DataTypes/QName_enumeration004_1371/QName_enumeration004_1371.v', REASONS.libxmlRejectsSerialized],
  ['DataTypes/QName006_2089/QName006_2089.v', REASONS.libxmlRejectsSerialized],
  ['DataTypes/short_pattern001_1658/short_pattern001_1658.v', REASONS.patternOnNonString],
  ['DataTypes/unsignedByte_pattern001_1802/unsignedByte_pattern001_1802.v', REASONS.patternOnNonString],
  ['DataTypes/unsignedInt_pattern001_1754/unsignedInt_pattern001_1754.v', REASONS.patternOnNonString],
  ['DataTypes/unsignedLong_pattern001_1730/unsignedLong_pattern001_1730.v', REASONS.patternOnNonString],
  ['DataTypes/unsignedLong005_2211/unsignedLong005_2211.v', REASONS.integerBeyondSafeInt],
  ['DataTypes/unsignedLong007_2213/unsignedLong007_2213.v', REASONS.integerBeyondSafeInt],
  ['DataTypes/unsignedShort_pattern001_1778/unsignedShort_pattern001_1778.v', REASONS.patternOnNonString],
  ['ElemDecl/abstract00101m/abstract00101m1_p', REASONS.requiredArrayEmpty],
  ['ElemDecl/disallowedsubst00301m1/Positive', REASONS.substitutionGroups],
  ['ElemDecl/disallowedsubst00401m1/Positive', REASONS.substitutionGroups],
  ['ElemDecl/disallowedsubst00501m1/Positive', REASONS.substitutionGroups],
  ['ElemDecl/disallowedsubst00502m1/Positive', REASONS.substitutionGroups],
  ['ElemDecl/disallowedsubst00502m2/Positive', REASONS.substitutionGroups],
  ['ElemDecl/disallowedsubst00503m1/Positive', REASONS.substitutionGroups],
  ['ElemDecl/disallowedsubst00503m2/Positive', REASONS.substitutionGroups],
  ['ElemDecl/substgrpaffil00101m/substGrpAffil00101m1_p', REASONS.requiredArrayEmpty],
  ['ElemDecl/targetns00101m/targetNS00101m1_p', REASONS.needsTriage],
  ['ElemDecl/typedef00205m/typeDef00205m1_p', REASONS.anyTypeContent],
  ['ElemDecl/typedef00802m1/Positive', REASONS.patternOnNonString],
  ['ElemDecl/typedef01301m1/Positive', REASONS.anyTypeContent],
  ['ElemDecl/valueconstraint00501m1/Positive', REASONS.patternOnNonString],
  ['ElemDecl/valueconstraint00501m2/Positive', REASONS.patternOnNonString],
  ['ElemDecl/valueconstraint00501m4/Positive', REASONS.patternOnNonString],
  ['ElemDecl/valueconstraint00501m5/Positive', REASONS.patternOnNonString],
  ['ElemDecl/valueconstraint00601m5/Positive', REASONS.patternOnNonString],
  ['ElemDecl/valueconstraint00601m7/Positive', REASONS.patternOnNonString],
  ['Element/elemO004/elemO004.v', REASONS.integerBeyondSafeInt],
  ['Element/elemO005/elemO005.v', REASONS.integerBeyondSafeInt],
  ['Element/elemS002/elemS002.v', REASONS.needsTriage],
  ['Element/elemS003/elemS003.v', REASONS.substitutionGroups],
  ['Element/elemS007/elemS007.v', REASONS.substitutionGroups],
  ['Element/elemS008/elemS008.v', REASONS.needsTriage],
  ['Element/elemU005/elemU005.v', REASONS.patternTranslation],
  ['Element/elemU006/elemU006.v', REASONS.patternTranslation],
  ['Element/elemU007/elemU007.v', REASONS.patternTranslation],
  ['Element/elemZ021d/elemZ021d.v', REASONS.anyTypeContent],
  ['Element/QFE1700c2/QFE1700c2.v', REASONS.needsTriage],
  ['Errata10/errC001/errC001.v', REASONS.needsTriage],
  ['Group/groupF009v/groupF009v.v', REASONS.libxmlRejectsSerialized],
  ['Group/groupG004v/groupG004v.v', REASONS.requiredArrayEmpty],
  ['Group/groupH009v/groupH009v.v', REASONS.libxmlRejectsSerialized],
  ['Group/groupH011v/groupH011v.v', REASONS.choiceValidation],
  ['Group/groupH014v/groupH014v.v', REASONS.choiceValidation],
  ['Group/groupH017v/groupH017v.v', REASONS.needsTriage],
  ['Group/groupH018v/groupH018v.v', REASONS.choiceValidation],
  ['Group/groupJ009v/groupJ009v.v', REASONS.libxmlRejectsSerialized],
  ['Group/groupL009v/groupL009v.v', REASONS.libxmlRejectsSerialized],
  ['Group/groupN009v/groupN009v.v', REASONS.libxmlRejectsSerialized],
  ['MGroup/compositor00202m1/Positive', REASONS.undefinedValue],
  ['MGroup/particles00203m1/Positive', REASONS.undefinedValue],
  ['MGroup/particles00301m1/Positive', REASONS.integerBeyondSafeInt],
  ['MGroup/particles00302m1/Positive', REASONS.integerBeyondSafeInt],
  ['ModelGroups/mgA015/mgA015.v', REASONS.libxmlRejectsSerialized],
  ['ModelGroups/mgF010/mgF010.v', REASONS.wildcard],
  ['ModelGroups/mgF011/mgF011.v', REASONS.wildcard],
  ['ModelGroups/mgF012/mgF012.v', REASONS.wildcard],
  ['ModelGroups/mgF014/mgF014.v', REASONS.wildcard],
  ['ModelGroups/mgF019/mgF019.v', REASONS.libxmlRejectsSerialized],
  ['ModelGroups/mgI009/mgI009.v', REASONS.choiceValidation],
  ['ModelGroups/mgI010/mgI010.v', REASONS.needsTriage],
  ['ModelGroups/mgI011/mgI011.v', REASONS.needsTriage],
  ['ModelGroups/mgI012/mgI012.v', REASONS.choiceValidation],
  ['ModelGroups/mgI013/mgI013.v', REASONS.needsTriage],
  ['ModelGroups/mgI014/mgI014.v', REASONS.choiceValidation],
  ['ModelGroups/mgI015/mgI015.v', REASONS.choiceValidation],
  ['ModelGroups/mgI016/mgI016.v', REASONS.anyTypeContent],
  ['ModelGroups/mgI017/mgI017.v', REASONS.anyTypeContent],
  ['ModelGroups/mgI018/mgI018.v', REASONS.choiceValidation],
  ['ModelGroups/mgO006/mgO006.v', REASONS.libxmlRejectsSerialized],
  ['ModelGroups/mgQ002/mgQ002.v', REASONS.libxmlRejectsSerialized],
  ['ModelGroups/mgQ003/mgQ003.v', REASONS.choiceValidation],
  ['NISTXMLSchemaDatatypes/atomic-decimal-maxExclusive-1/NISTXML-SV-IV-atomic-decimal-maxExclusive-2-5', REASONS.facetPrecision],
  ['NISTXMLSchemaDatatypes/atomic-decimal-maxExclusive-2/NISTXML-SV-IV-atomic-decimal-maxExclusive-3-5', REASONS.facetPrecision],
  ['NISTXMLSchemaDatatypes/atomic-decimal-maxExclusive-3/NISTXML-SV-IV-atomic-decimal-maxExclusive-4-5', REASONS.facetPrecision],
  ['NISTXMLSchemaDatatypes/atomic-decimal-maxExclusive-4/NISTXML-SV-IV-atomic-decimal-maxExclusive-5-5', REASONS.facetPrecision],
  ['NISTXMLSchemaDatatypes/atomic-decimal-maxExclusive/NISTXML-SV-IV-atomic-decimal-maxExclusive-1-1', REASONS.facetPrecision],
  ['NISTXMLSchemaDatatypes/atomic-decimal-minExclusive-1/NISTXML-SV-IV-atomic-decimal-minExclusive-2-1', REASONS.facetPrecision],
  ['NISTXMLSchemaDatatypes/atomic-decimal-minExclusive-2/NISTXML-SV-IV-atomic-decimal-minExclusive-3-1', REASONS.facetPrecision],
  ['NISTXMLSchemaDatatypes/atomic-decimal-minExclusive-3/NISTXML-SV-IV-atomic-decimal-minExclusive-4-1', REASONS.facetPrecision],
  ['NISTXMLSchemaDatatypes/atomic-decimal-minExclusive-4/NISTXML-SV-IV-atomic-decimal-minExclusive-5-1', REASONS.facetPrecision],
  ['NISTXMLSchemaDatatypes/atomic-decimal-minExclusive/NISTXML-SV-IV-atomic-decimal-minExclusive-1-1', REASONS.facetPrecision],
  ['NISTXMLSchemaDatatypes/atomic-decimal-pattern-2/NISTXML-SV-IV-atomic-decimal-pattern-3-4', REASONS.patternOnNonString],
  ['NISTXMLSchemaDatatypes/atomic-decimal-pattern-4/NISTXML-SV-IV-atomic-decimal-pattern-5-1', REASONS.patternOnNonString],
  ['NISTXMLSchemaDatatypes/atomic-decimal-pattern-4/NISTXML-SV-IV-atomic-decimal-pattern-5-2', REASONS.patternOnNonString],
  ['NISTXMLSchemaDatatypes/atomic-decimal-pattern-4/NISTXML-SV-IV-atomic-decimal-pattern-5-3', REASONS.patternOnNonString],
  ['NISTXMLSchemaDatatypes/atomic-decimal-pattern-4/NISTXML-SV-IV-atomic-decimal-pattern-5-4', REASONS.patternOnNonString],
  ['NISTXMLSchemaDatatypes/atomic-decimal-pattern-4/NISTXML-SV-IV-atomic-decimal-pattern-5-5', REASONS.patternOnNonString],
  ['Particles/particlesA006/particlesA006.v', REASONS.libxmlRejectsSerialized],
  ['Particles/particlesA007/particlesA007.v', REASONS.libxmlRejectsSerialized],
  ['Particles/particlesB013/particlesB013.v', REASONS.wildcard],
  ['Particles/particlesDc001/particlesDc001.v', REASONS.anyTypeContent],
  ['Particles/particlesDc002/particlesDc002.v', REASONS.anyTypeContent],
  ['Particles/particlesDc003/particlesDc003.v', REASONS.anyTypeContent],
  ['Particles/particlesDc007/particlesDc007.v', REASONS.anyTypeContent],
  ['Particles/particlesEb027/particlesEb027.v', REASONS.libxmlRejectsSerialized],
  ['Particles/particlesEb036/particlesEb036.v', REASONS.libxmlRejectsSerialized],
  ['Particles/particlesEb038/particlesEb038.v', REASONS.libxmlRejectsSerialized],
  ['Particles/particlesHa015/particlesHa015.v', REASONS.anyTypeContent],
  ['Particles/particlesIb005/particlesIb005.v', REASONS.anyTypeContent],
  ['Particles/particlesIe004/particlesIe004.v', REASONS.choiceValidation],
  ['Particles/particlesJs001/particlesJs001.v', REASONS.libxmlRejectsSerialized],
  ['Particles/particlesOb003/particlesOb003.v', REASONS.wildcard],
  ['Particles/particlesOb006/particlesOb006.v', REASONS.wildcard],
  ['Particles/particlesOb007/particlesOb007.v', REASONS.wildcard],
  ['Particles/particlesOb012/particlesOb012.v', REASONS.wildcard],
  ['Particles/particlesOb015/particlesOb015.v', REASONS.wildcard],
  ['Particles/particlesOb022/particlesOb022.v', REASONS.libxmlRejectsSerialized],
  ['Particles/particlesOb042/particlesOb042.v', REASONS.strictWildcardHarness],
  ['Particles/particlesOb047/particlesOb047.v', REASONS.wildcard],
  ['Particles/particlesOb048/particlesOb048.v', REASONS.wildcard],
  ['Particles/particlesOb052/particlesOb052.v', REASONS.libxmlRejectsSerialized],
  ['Particles/particlesOb054/particlesOb054.v', REASONS.wildcard],
  ['Particles/particlesOb057/particlesOb057.v', REASONS.wildcard],
  ['Particles/particlesOb059/particlesOb059.v', REASONS.wildcard],
  ['Particles/particlesOb060/particlesOb060.v', REASONS.wildcard],
  ['Particles/particlesQ013/particlesQ013.v', REASONS.libxmlRejectsSerialized],
  ['Particles/particlesQ017/particlesQ017.v', REASONS.libxmlRejectsSerialized],
  ['Particles/particlesQ024/particlesQ024.v', REASONS.needsTriage],
  ['Particles/particlesQ030/particlesQ030.v', REASONS.libxmlRejectsSerialized],
  ['Particles/particlesQ032/particlesQ032.v', REASONS.libxmlRejectsSerialized],
  ['Particles/particlesR016/particlesR016.v', REASONS.libxmlRejectsSerialized],
  ['Particles/particlesR022/particlesR022.v', REASONS.libxmlRejectsSerialized],
  ['Particles/particlesT003/particlesT003.v', REASONS.choiceValidation],
  ['Particles/particlesV003/particlesV003.v', REASONS.libxmlRejectsSerialized],
  ['Particles/particlesZ003/particlesZ003.v', REASONS.libxmlRejectsSerialized],
  ['Particles/particlesZ005/particlesZ005.v', REASONS.needsTriage],
  ['Particles/particlesZ012/particlesZ012.v', REASONS.needsTriage],
  ['Particles/particlesZ034_a1/particlesZ034_a1.v', REASONS.libxmlRejectsSerialized],
  ['Schema/schD7/schD7.v', REASONS.fileResolution],
  ['Schema/schG8/schG8.v', REASONS.fileResolution],
  ['SimpleType/stE050/stE050.v', REASONS.libxmlRejectsSerialized],
  ['SimpleType/stE055/stE055.v', REASONS.needsTriage],
  ['SimpleType/stE065/stE065.v', REASONS.libxmlRejectsSerialized],
  ['SimpleType/stE066/stE066.v', REASONS.libxmlRejectsSerialized],
  ['SimpleType/stE079/stE079.v', REASONS.libxmlRejectsSerialized],
  ['SimpleType/stE091/stE091.v', REASONS.libxmlRejectsSerialized],
  ['SimpleType/stE092/stE092.v', REASONS.libxmlRejectsSerialized],
  ['SimpleType/stE093/stE093.v', REASONS.libxmlRejectsSerialized],
  ['SimpleType/stE094/stE094.v', REASONS.libxmlRejectsSerialized],
  ['SimpleType/stG001/stG001.v', REASONS.integerBeyondSafeInt],
  ['SimpleType/stG006/stG006.v', REASONS.integerBeyondSafeInt],
  ['SimpleType/stG010/stG010.v', REASONS.needsTriage],
  ['SimpleType/stH003/stH003.v', REASONS.patternOnNonString],
  ['SimpleType/stH007/stH007.v', REASONS.needsTriage],
  ['SimpleType/stZ040/stZ040.v', REASONS.needsTriage],
  ['SimpleType/stZ046/stZ046.v', REASONS.requiredArrayEmpty],
  ['SimpleType/stZ054/stZ054.v', REASONS.anyTypeContent],
  ['SimpleType/stZ072/stZ072.v', REASONS.needsTriage],
  ['SType/st_name00401m/ST_name00401m1_p', REASONS.needsTriage],
  ['SType/st_targetns00101m/ST_targetNS00101m1_p', REASONS.needsTriage],
  ['SType/st_targetns00101m/ST_targetNS00101m2_p', REASONS.needsTriage],
  ['SType/st_targetns00201m/ST_targetNS00201m1_p', REASONS.needsTriage],
  ['suntest/xsd001/xsd001.v00', REASONS.needsTriage],
  ['suntest/xsd001/xsd001.v01', REASONS.needsTriage],
  ['suntest/xsd001/xsd001.v02', REASONS.needsTriage],
  ['suntest/xsd001/xsd001.v03', REASONS.needsTriage],
  ['suntest/xsd008/xsd008.v00', REASONS.requiredArrayEmpty],
]);
