// Known failures for the W3C sun/ms selection (#108), keyed by
// `<testSetName>/<testGroup>/<instanceTest>`. Each entry pins a genuine bug
// or an unsupported feature with its reason. Entries run as `it.fails`, so a
// fix that makes a case pass turns the suite red — remove the entry in the
// same PR that lands the fix. Generated from a full vitest run, then
// hand-maintained.
export const REASONS = {
  undefinedValue: "parse: element value arrives as undefined (needs triage)",
  anyTypeContent: "unsupported: xs:anyType content (element without a type maps to xs:string)",
  wildcard: "unsupported: xs:any wildcard content",
  strictWildcardHarness:
    "strict wildcard: extras re-serialized faithfully, but single-schema libxml2 validation cannot see cross-file declarations (harness limitation)",
  libxmlRejectsSerialized: "libxml2 rejects serialized XML (needs triage)",
  needsTriage: "needs triage",
  patternOnNonString:
    "runtime: pattern checked against coerced value, not the original lexical (lexical preservation needed)",
  choiceDocumentOrder:
    "choice: interleaved repeated branches collapse into per-element arrays; document order is lost and the serialized XML no longer validates",
  requiredArrayEmpty: "cardinality: required element array parsed empty (needs triage)",
  unionCoercion: "runtime: union member coercion rejects a valid value (needs triage)",
  simpleContentShape: "parse: simpleContent _text shape mismatch (needs triage)",
  fileResolution: "harness: test-set file resolution (needs triage)",
} as const;

export const W3C_KNOWN_FAILURES = new Map<string, string>([
  ["Additional/addB012/addB012.v", REASONS.libxmlRejectsSerialized],
  ["Additional/addB067/addB067.v", REASONS.libxmlRejectsSerialized],
  ["Additional/addB068/addB068.i", REASONS.libxmlRejectsSerialized],
  ["Additional/addB090/addB090.v", REASONS.wildcard],
  ["Additional/addB116/addB116.v", REASONS.strictWildcardHarness],
  ["Additional/addB135/addB135.v", REASONS.wildcard],
  ["Additional/addB187/addB187.v", REASONS.needsTriage],
  ["Additional/addC001/addC001.v", REASONS.undefinedValue],
  ["Additional/isDefault072/isDefault072.v", REASONS.undefinedValue],
  ["Additional/isDefault078/isDefault078.v", REASONS.libxmlRejectsSerialized],
  ["Additional/isDefault079/isDefault079.v", REASONS.needsTriage],
  ["Additional/memberType004/memberType004.v", REASONS.libxmlRejectsSerialized],
  ["Additional/memberType008/memberType008.v", REASONS.libxmlRejectsSerialized],
  ["Attribute/attO009/attO009.v", REASONS.needsTriage],
  ["Attribute/attO010/attO010.v", REASONS.needsTriage],
  ["Attribute/attO011/attO011.v", REASONS.needsTriage],
  ["AttributeGroup/attgD019/attgD019.v", REASONS.strictWildcardHarness],
  ["AttributeGroup/attgD020/attgD020.v", REASONS.strictWildcardHarness],
  ["AttributeGroup/attgD021/attgD021.v", REASONS.strictWildcardHarness],
  ["AttributeGroup/attgD022/attgD022.v", REASONS.strictWildcardHarness],
  ["AttributeGroup/attgD025/attgD025.v", REASONS.strictWildcardHarness],
  ["AttributeGroup/attgD034/attgD034.v", REASONS.strictWildcardHarness],
  ["ComplexType/ctA002/ctA002.v", REASONS.libxmlRejectsSerialized],
  ["ComplexType/ctA003/ctA003.v", REASONS.libxmlRejectsSerialized],
  ["ComplexType/ctL021/ctL021.v", REASONS.strictWildcardHarness],
  ["ComplexType/ctL022/ctL022.v", REASONS.libxmlRejectsSerialized],
  ["ComplexType/ctZ007/ctZ007.v", REASONS.requiredArrayEmpty],
  ["CType/basetd00101m1/Positive", REASONS.simpleContentShape],
  ["CType/basetd00101m2/Positive", REASONS.simpleContentShape],
  ["CType/targetns00101m/targetNS00101m1_p", REASONS.needsTriage],
  ["DataTypes/gMonth002_2061/gMonth002_2061.v", REASONS.libxmlRejectsSerialized],
  ["DataTypes/gMonth004_2063/gMonth004_2063.v", REASONS.libxmlRejectsSerialized],
  [
    "DataTypes/QName_enumeration002_1369/QName_enumeration002_1369.v",
    REASONS.libxmlRejectsSerialized,
  ],
  [
    "DataTypes/QName_enumeration004_1371/QName_enumeration004_1371.v",
    REASONS.libxmlRejectsSerialized,
  ],
  ["DataTypes/QName006_2089/QName006_2089.v", REASONS.libxmlRejectsSerialized],
  ["ElemDecl/targetns00101m/targetNS00101m1_p", REASONS.needsTriage],
  ["ElemDecl/typedef01301m1/Positive", REASONS.anyTypeContent],
  ["ElemDecl/valueconstraint00501m1/Positive", REASONS.patternOnNonString],
  ["ElemDecl/valueconstraint00501m2/Positive", REASONS.patternOnNonString],
  ["ElemDecl/valueconstraint00501m4/Positive", REASONS.patternOnNonString],
  ["ElemDecl/valueconstraint00501m5/Positive", REASONS.patternOnNonString],
  ["ElemDecl/valueconstraint00601m7/Positive", REASONS.patternOnNonString],
  ["Element/QFE1700c2/QFE1700c2.v", REASONS.needsTriage],
  ["Errata10/errC001/errC001.v", REASONS.needsTriage],
  ["Group/groupF009v/groupF009v.v", REASONS.libxmlRejectsSerialized],
  ["Group/groupH009v/groupH009v.v", REASONS.libxmlRejectsSerialized],
  ["Group/groupH014v/groupH014v.v", REASONS.choiceDocumentOrder],
  ["Group/groupH017v/groupH017v.v", REASONS.needsTriage],
  ["Group/groupH018v/groupH018v.v", REASONS.choiceDocumentOrder],
  ["Group/groupJ009v/groupJ009v.v", REASONS.libxmlRejectsSerialized],
  ["Group/groupL009v/groupL009v.v", REASONS.libxmlRejectsSerialized],
  ["Group/groupN009v/groupN009v.v", REASONS.libxmlRejectsSerialized],
  ["MGroup/compositor00202m1/Positive", REASONS.undefinedValue],
  ["MGroup/particles00203m1/Positive", REASONS.undefinedValue],
  ["ModelGroups/mgA015/mgA015.v", REASONS.libxmlRejectsSerialized],
  ["ModelGroups/mgF010/mgF010.v", REASONS.wildcard],
  ["ModelGroups/mgF011/mgF011.v", REASONS.wildcard],
  ["ModelGroups/mgF012/mgF012.v", REASONS.wildcard],
  ["ModelGroups/mgF014/mgF014.v", REASONS.wildcard],
  ["ModelGroups/mgF019/mgF019.v", REASONS.libxmlRejectsSerialized],
  ["ModelGroups/mgI010/mgI010.v", REASONS.needsTriage],
  ["ModelGroups/mgI011/mgI011.v", REASONS.needsTriage],
  ["ModelGroups/mgI013/mgI013.v", REASONS.needsTriage],
  ["ModelGroups/mgI016/mgI016.v", REASONS.anyTypeContent],
  ["ModelGroups/mgI017/mgI017.v", REASONS.anyTypeContent],
  ["ModelGroups/mgO006/mgO006.v", REASONS.libxmlRejectsSerialized],
  ["ModelGroups/mgQ002/mgQ002.v", REASONS.libxmlRejectsSerialized],
  ["ModelGroups/mgQ003/mgQ003.v", REASONS.choiceDocumentOrder],
  ["Particles/particlesA006/particlesA006.v", REASONS.libxmlRejectsSerialized],
  ["Particles/particlesA007/particlesA007.v", REASONS.libxmlRejectsSerialized],
  ["Particles/particlesB013/particlesB013.v", REASONS.wildcard],
  ["Particles/particlesEb027/particlesEb027.v", REASONS.libxmlRejectsSerialized],
  ["Particles/particlesEb036/particlesEb036.v", REASONS.libxmlRejectsSerialized],
  ["Particles/particlesEb038/particlesEb038.v", REASONS.libxmlRejectsSerialized],
  ["Particles/particlesHa015/particlesHa015.v", REASONS.anyTypeContent],
  ["Particles/particlesJs001/particlesJs001.v", REASONS.libxmlRejectsSerialized],
  ["Particles/particlesOb003/particlesOb003.v", REASONS.wildcard],
  ["Particles/particlesOb006/particlesOb006.v", REASONS.wildcard],
  ["Particles/particlesOb007/particlesOb007.v", REASONS.wildcard],
  ["Particles/particlesOb012/particlesOb012.v", REASONS.wildcard],
  ["Particles/particlesOb015/particlesOb015.v", REASONS.wildcard],
  ["Particles/particlesOb022/particlesOb022.v", REASONS.libxmlRejectsSerialized],
  ["Particles/particlesOb042/particlesOb042.v", REASONS.strictWildcardHarness],
  ["Particles/particlesOb047/particlesOb047.v", REASONS.wildcard],
  ["Particles/particlesOb048/particlesOb048.v", REASONS.wildcard],
  ["Particles/particlesOb052/particlesOb052.v", REASONS.libxmlRejectsSerialized],
  ["Particles/particlesOb054/particlesOb054.v", REASONS.wildcard],
  ["Particles/particlesOb057/particlesOb057.v", REASONS.wildcard],
  ["Particles/particlesOb059/particlesOb059.v", REASONS.wildcard],
  ["Particles/particlesOb060/particlesOb060.v", REASONS.wildcard],
  ["Particles/particlesQ013/particlesQ013.v", REASONS.libxmlRejectsSerialized],
  ["Particles/particlesQ017/particlesQ017.v", REASONS.libxmlRejectsSerialized],
  ["Particles/particlesQ024/particlesQ024.v", REASONS.needsTriage],
  ["Particles/particlesQ030/particlesQ030.v", REASONS.libxmlRejectsSerialized],
  ["Particles/particlesQ032/particlesQ032.v", REASONS.libxmlRejectsSerialized],
  ["Particles/particlesR016/particlesR016.v", REASONS.libxmlRejectsSerialized],
  ["Particles/particlesR022/particlesR022.v", REASONS.libxmlRejectsSerialized],
  ["Particles/particlesV003/particlesV003.v", REASONS.libxmlRejectsSerialized],
  ["Particles/particlesZ003/particlesZ003.v", REASONS.libxmlRejectsSerialized],
  ["Particles/particlesZ005/particlesZ005.v", REASONS.needsTriage],
  ["Particles/particlesZ012/particlesZ012.v", REASONS.needsTriage],
  ["Particles/particlesZ034_a1/particlesZ034_a1.v", REASONS.libxmlRejectsSerialized],
  ["SimpleType/stE065/stE065.v", REASONS.libxmlRejectsSerialized],
  ["SimpleType/stE066/stE066.v", REASONS.libxmlRejectsSerialized],
  ["SimpleType/stE079/stE079.v", REASONS.libxmlRejectsSerialized],
  ["SimpleType/stE094/stE094.v", REASONS.libxmlRejectsSerialized],
  ["SimpleType/stZ054/stZ054.v", REASONS.anyTypeContent],
  ["SimpleType/stZ072/stZ072.v", REASONS.needsTriage],
  ["SType/st_name00401m/ST_name00401m1_p", REASONS.needsTriage],
  ["SType/st_targetns00101m/ST_targetNS00101m1_p", REASONS.needsTriage],
  ["SType/st_targetns00101m/ST_targetNS00101m2_p", REASONS.needsTriage],
  ["SType/st_targetns00201m/ST_targetNS00201m1_p", REASONS.needsTriage],
  ["suntest/xsd001/xsd001.v00", REASONS.needsTriage],
  ["suntest/xsd001/xsd001.v01", REASONS.needsTriage],
  ["suntest/xsd001/xsd001.v02", REASONS.needsTriage],
  ["suntest/xsd001/xsd001.v03", REASONS.needsTriage],
]);
